### ISSUE TITLE
Summary of feature availability

### ISSUE THREAD

**Issue by frandevel** [vaadin/spring#1]
Would be really nice to have a small summary of what parts of the former project are still available in this addon. The same way it was on the readme of the Vaadin4Spring project. Or can we use the former readme as a state of this addon?
Thanks

**Comment by peholmst** [comment]
I don't have the entire roadmap at hand right now, but IIRC, the first version will only contain the scopes (Session, UI and View) and support for the Navigation API (view provider). In addition, the add-on will work both with vanilla Spring and Spring Boot.

In the future, some other parts of Vaadin4Spring will probably also be migrated into the official add-on, whereas other parts will not. Vaadin4Spring will, however, continue to live as an unofficial add-on for the official add-on.

**Comment by frandevel** [comment]
Thanks a lot for the quick response @peholmst . In any case the parts we're using right now in our projects need only this initial features. Good to hear.

**Comment by pleku** [comment]
(this issue was for the previous un-official add-on)
