### ISSUE TITLE
Actuator endpoints

### ISSUE THREAD

**Issue by koenraadva** [vaadin/spring#10]
Actuator endpoints are not working (/env, /health,...)
workaround is to include a url mapping in the application.properties
e.g. vaadin.servlet.urlMapping=/myapp/*

**Comment by hesara** [comment]
This (and the more general underlying issue of Vaadin and Spring MVC compatibility when the Vaadin application should be served at the context root) is something we are still trying to resolve for Vaadin Spring Boot 1.0. We do have a prototype of a solution that works in basic cases by forwarding requests, but we are not satisfied with the approach as it could cause complications e.g. with push so we are trying to implement this using another approach.

In the meanwhile, workarounds include either mapping the Vaadin servlet to another path as you suggested or running the Spring Actuator server at a different port (e.g. management.port=8081).

**Comment by hesara** [comment]
This issue (Vaadin Spring Boot at root context together with Spring MVC/Actuator with such mappings) has already been fixed in 1.0.0.beta3.
