### ISSUE TITLE
vaadin.whitelisted-packages breaks LitRenderer

### ISSUE THREAD

**Issue by Frettman** [vaadin/spring#1008]
Any non-trivial Spring Boot application seems to require `vaadin.whitelisted-packages` to be set, otherwise the application start takes much too long, at least in dev mode.
But when I set the whitelist to the root package of my application, there seem to be some built-in parts of Vaadin that break. More specifically I experience this for the `com.vaadin.flow.data.renderer.LitRenderer`. I can find `lit-renderer.ts` in `target/flow-frontend` but it does not seem to get loaded: `window.Vaadin.setLitRenderer is not a function`.
When I remove the whitelist and restart the application it starts working again.
Adding `com.vaadin` to the whitelist also seems to do the trick. But I was under the impression this shouldn't be necessary? At least there doesn't seem to be any mention of this anywhere.

As I have mentioned in #620, I would really appreciate a mechanism that allows add-ons to automatically contribute packages that they need to have scanned. This would make having to micromanage `vaadin.whitelisted-packages` obsolete in the first place.

**Comment by caalador** [comment]
The default scanned packages for a whitelist always include the package of `Component` (`com.vaadin.flow.component`), `Theme` (`com.vaadin.flow.theme`) and `com.vaadin.shrinkwrap` as those have been the only places with annotations to take into account as renderers have not used any annotations.

Seems this changed in 22.0.0.alpha2 when LitRenderer was added.
