### ISSUE TITLE
INVOICE VIEW

### ISSUE THREAD

**Issue by cosmah** [vaadin/spring#1078]
![image](https://github.com/vaadin/spring/assets/101720284/19fa0b24-1ed0-4041-9ba1-f76e50872e45)
Hello everyone, can anyone please assist in how to create a view like this in vaadin?

**Comment by mcollovati** [comment]
To ask for generic usage help, it is better to use Vaadin [Discord](https://discord.gg/MYFq5RTbBn) server.
GitHub issues are better suited for bug reports or enhancement requests

**Comment by mshabarov** [comment]
Based on the picture you provided, you may want to use the following Vaadin components/API (when you make your UI with Vaadin Flow): `Grid`, [ComponentRenderer](https://vaadin.com/docs/latest/components/grid/flow#using-component-renderers), `VaadinIcon`, [Tooltip](https://vaadin.com/docs/latest/components/tooltip), and also [button layouting examples](https://vaadin.com/docs/latest/components/button#best-practices).
