### ISSUE TITLE
Vaadin URLMapping does not work for UIDL Requests with 1.0.0.beta3

### ISSUE THREAD

**Issue by pesse** [vaadin/spring#11]
Hey,

I ran into a strange problem today when updating my project to 1.0.0.beta3: I run my Vaadin Servelet with `vaadin.servlet.urlMapping=/ui/*`. It works well when I enter the URL directly in the browser, but when I access any function which does a UIDL-Request I get a "Communication problem", caused by `405 Method Not Allowed`.
The UIDL-Request which is sent is `http://localhost:8080/UIDL/?v-wsver=7.4.4&v-uiId=0` - *without* the `/ui/`part.

Startup log says the mapping worked, though:
````
2015-04-29 15:12:36.209  INFO 25008 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'springVaadinServlet' to [/ui, /ui/*, /VAADIN/*]
````

With 1.0.0.beta2 everything works fine.
Problem also exists in current version 1.0.0-SNAPSHOT

Edit: Opened Trac-Defect #17682

**Comment by markoradinovic** [comment]
I just switch to official Spring plugin (from vaadin4spring version) and I have the same problem. In my case even changing plugin version to 1.0.0.beta2 doesn't help. Application is running fine if I don't use custom urlMapping. Unfortunately, I can't use default urlMapping because of conflict with REST and Actuator endpoints.

**Comment by samie** [comment]
Should be fixed in https://dev.vaadin.com/ticket/17682

**Comment by hesara** [comment]
Should already be fixed in master, will be included in the next release. With correctly formed mappings and a slash at the end of the path with which the page is opened, this should also work with 1.0.0.beta3. Please comment in Vaadin Trac if this still doesn't work when the next release is out.
