### ISSUE TITLE
ViewContainer annotations on multiple UIs cause a conflict to be reported

### ISSUE THREAD

**Issue by hesara** [vaadin/spring#113]
If multiple UI classes have the @ViewContainer annotation, an exception about multiple ViewContainers is thrown. The ViewContainers of different UIs should not cause conflicts.

This should apply both to @ViewContainer on beans and @ViewContainer on fields.

**Comment by elmot** [comment]
Also happens if several UI instances of the same class are created in one session

**Comment by elmot** [comment]
https://github.com/vaadin/spring/pull/117

**Comment by hesara** [comment]
This is addressed by #118
