### ISSUE TITLE
Vaadin spring boot

### ISSUE THREAD

**Issue by ffazil** [vaadin/spring#12]
How do i recompile/update widgetsets using vaadin spring boot?

**Comment by hesara** [comment]
There is nothing special about that - use the Vaadin Maven plug-in or equivalent IDE integration. See e.g. https://github.com/vaadin/archetype-application-example/blob/master/mockapp-widgetset/pom.xml for an example of the configuration of vaadin-maven-plugin. Then use @Widgetset for your UI class to configure the widgetset used.
