### ISSUE TITLE
Subscribing to event bus more than once calls listeners many times

### ISSUE THREAD

**Issue by MTzukanov** [vaadin/spring#121]
Unsubscribing, however, is enough only once, all the listener instances are unsubscribed at once.

**Comment by hesara** [comment]
Which event bus? It seems to me that this is not about the Vaadin Spring add-on, but the vaadin4spring add-on (https://github.com/peholmst/vaadin4spring) which is on top of Vaadin Spring and provides event bus support? Please create a ticket with more details there.
