### ISSUE TITLE
Best practice for i18n with boot autoconfig

### ISSUE THREAD

**Issue by eiswind** [vaadin/spring#14]
in
https://github.com/peholmst/vaadin-spring-webinar/tree/master/i18n

its suggested to extend vaadin serlvet. how would you suggest to replace the vaadinservlet from the autoconfiguration, so that it can handle i18n properly?

**Comment by hesara** [comment]
If I recall correctly, it might be possible to override the default servlet by extending com.vaadin.spring.boot.internal.VaadinServletConfiguration and overriding the method vaadinServlet().

In the future, we would like to make such customizations easier (see e.g. https://dev.vaadin.com/ticket/18206) and move VaadinServletConfiguration out of the "internal" package.  The default configuration in Vaadin Spring Boot should use conditional beans to "back off" when a bean by that name has already been declared. This is not yet implemented in the add-on, though, and will be tracked in 18206.
