### ISSUE TITLE
Cannot use auto-configuration without com.vaadin.spring.navigator.SpringNavigator

### ISSUE THREAD

**Issue by snicoll** [vaadin/spring#151]
`VaadinAutoConfiguration` has a constructs where it checks if a bean of a certain type is missing and if that's the case, auto-configures one. What is particular about this example is that it uses a `String` literal (rather than a `Class` literal) to references the target type.

You can't really do that without some more guards. That condition is going to inspect the application context for a bean of that type and will have to load the class in order to do so. I am happy to offer a PR if you want me to.

You can reproduce by upgrading the starter in the [`spring-data-vaadin-crud` sample project](https://github.com/mstahv/spring-data-vaadin-crud).

**Comment by mstahv** [comment]
Dough :-( It still worked with rc2. I'll try to find the team to create a 1.0.1 really soon with this fix.
