### ISSUE TITLE
Create a BOM for Vaadin Spring

### ISSUE THREAD

**Issue by hesara** [vaadin/spring#153]
To avoid problems where a transitive dependency brings a different version of vaadin-spring than what e.g. vaadin-spring-boot-starter expects, there should be a BOM for Vaadin Spring.

Spring Initializr (start.spring.io) should be updated to use the BOM when this ticket is resolved.

**Comment by snicoll** [comment]
Thanks Henri! I'd like to review this one to make sure the integration on start.spring.io will have the right expectations.

**Comment by pleku** [comment]
The Vaadin Framework & Vaadin Spring versions are now in the Framework BOM, thus this ticket is considered done / invalid.
