### ISSUE TITLE
Legacy Configuration Paramaters

### ISSUE THREAD

**Issue by knacht** [vaadin/spring#16]
Hello,

we just migrated our app from vaadin4spring to the officical addon, and everything seems to work fine. 
One thing i am missing are the two params 

`vaadin.servlet.params.productionMode`
`vaadin.servlet.params.widgetset`

Have they been renamed/removed?

**Comment by hesara** [comment]
Sorry for the late reply.

The production mode parameter was renamed to vaadin.servlet.productionMode.

As for the widgetset, this is covered by https://dev.vaadin.com/ticket/17703. Until that is implemented, please use @Widgetset on the UI class.
