### ISSUE TITLE
SpringViewDisplayRegistrationBean is not serializable and gives warning

### ISSUE THREAD

**Issue by gokhanoner** [vaadin/spring#160]
When using `@SpringViewDisplay`, below warning occours:

`WARN 10344 --- [nio-9292-exec-4] com.vaadin.spring.internal.BeanStore     : Storing non-serializable bean [com.vaadin.spring.internal.SpringViewDisplayRegistrationBean@8f7687] with name [com.vaadin.spring.internal.SpringViewDisplayRegistrationBean#0] in [UIBeanStore[id=11607e, name=UI:0]]`

**Comment by scipionyx** [comment]
This is very important, it is preventing a spring-vaadin application to be deployed on a HA application server.

**Comment by apolds** [comment]
When using with spring session (spring session data redis) this issue produces a NotSerializableException.
