### ISSUE TITLE
Support for spring-boot 1.5

### ISSUE THREAD

**Issue by iboyko** [vaadin/spring#170]
Deprecated class is used in spring/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java

Class `org.springframework.boot.context.embedded.ServletRegistrationBean` is deprecated as of 1.4 in favor of `org.springframework.boot.web.servlet.ServletRegistrationBean`.

Class `org.springframework.boot.context.embedded.ServletRegistrationBean` is removed in spring-boot 1.5.

**Comment by tstsogoo** [comment]
+

**Comment by snicoll** [comment]
Hello. Spring Boot 1.5 is out and I have no other choice than disabling the starter for 1.5+ on start.spring.io now. Let me know when that issue is resolved by creating an issue on https://github.com/spring-io/initializr

**Comment by snicoll** [comment]
Guys, this is something you can fix against 1.4 so could you please use the proper class (it's just an import change) and release a bug fix release of the current line? That way it should work with both 1.4 and 1.5 

Let me know if you need any help!
