### ISSUE TITLE
No Authentication in security context when using @Push

### ISSUE THREAD

**Issue by MariusKl** [vaadin/spring#176]
I would like to use @Push in my spring-boot application (1.4.2) with vaadin (7.7.), but after a successful login the Authentication in the SecurityContext is not available anymore. 

Relevant dependencies
```
<dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-spring</artifactId>
            <version>${vaadin-spring.version}</version>
</dependency>
<dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-push</artifactId>
            <version>${vaadin.version}</version>
</dependency>
<dependency>
            <groupId>org.vaadin.spring.extensions</groupId>
            <artifactId>vaadin-spring-ext-security</artifactId>
            <version>${vaadin-spring-ext.version}</version>
</dependency>
```

My application looks like
```
@SpringBootApplication
@EnableAsync
@Import(VaadinExtensionsConfiguration.class)
@EnableWebSecurity
@EnableGlobalMethodSecurity(securedEnabled = true, prePostEnabled = true, proxyTargetClass = true)
@EnableVaadinSharedSecurity
@EnableScheduling
@EnableSpringConfigured
@EnableLoadTimeWeaving(aspectjWeaving = EnableLoadTimeWeaving.AspectJWeaving.ENABLED)
@EnableAspectJAutoProxy
public class DummyApplication
```

I have a UI for the LoginView and a UI for all other views which are only available when logged in
```
@SpringUI
@Push public class DummyUI {
```

Calling `SecurityContextHolder.getContext().getAuthentication()` returns null when logged in. Without @Push I do not have any problems with the authentication.

I have seen https://vaadin.com/forum#!/thread/3383122 but non of the approaches works. Most of the comments on the internet are related to an older vaadin, vaadin-spring or spring4vaadin version, so I am wondering if there is some overall solution for that problem in the meanwhile.

**Comment by MariusKl** [comment]
In the end this was more about trying to get the authentication in another thread which obviously does not work

**Comment by AlvaroFalcon** [comment]
@MariusKl could you explain how you fixed this? Thanks :)
