### ISSUE TITLE
add to SpringView annotation

### ISSUE THREAD

**Issue by carljmosca** [vaadin/spring#18]
There seems to be some properties missing from the SpringView annotation [as compared to previous implementations].

Can some/all of these be added to the com.vaadin.spring.annotation.SpringView interface?

    public static final int END = Integer.MAX_VALUE;
    public static final int BEGINNING = 0;
    public static final int DEFAULT = 1000;

    public boolean enabled() default true;

    public String title() default "";

    public int order() default DEFAULT;
    
    public FontAwesome icon() default FontAwesome.FILE;

**Comment by peholmst** [comment]
I wonder if you are confusing the @SpringView annotation with the side bar in Vaadin4Spring?
Check https://github.com/peholmst/vaadin4spring/tree/master/addons/sidebar.

**Comment by carljmosca** [comment]
I don't think I was as much confused as not clear or perhaps complete.  I realize I can add the side bar but I would to see it, something like it, or an easy way to add similar in the official Vaadin Spring support.
