### ISSUE TITLE
SpringViewDisplayRegistrationBean needs to be serializable for Spring Session to work

### ISSUE THREAD

**Issue by scipionyx** [vaadin/spring#180]
SpringViewDisplayRegistrationBean needs to be serializable for Spring Session to work

**Comment by scipionyx** [comment]
it was closed with the pull request #181 , not sure how to proceed from here.

**Comment by hesara** [comment]
Fixed by #205 for the 1.2 branch, and already fixed earlier in master/2.0 branches.
