### ISSUE TITLE
Provide support for Spring-Boot-2

### ISSUE THREAD

**Issue by elmot** [vaadin/spring#190]
DoD: Working example of multimodule application for Vaadin 8 + Spring Boot 2 + vaadin-spring-boot 2.x.

**Comment by mrts** [comment]
Can you please include a custom theme and SASS compilation in the example?

**Comment by heruan** [comment]
Is this anywhere on the roadmap yet?

**Comment by buzdin** [comment]
Any updates on this roadmap item?

**Comment by tsuoanttila** [comment]
Just ran our integration test with `spring.boot.version=2.0.0.RELEASE`, I had to fix one import from a test class but other than that seems to run and work as expected. Was there something specific you needed for this ticket?

**Comment by snicoll** [comment]
I am confused about this issue. Vaadin is available on start.spring.io with Spring Boot 2.

**Comment by tsuoanttila** [comment]
Tested and works. Closing issue.

**Comment by tsuoanttila** [comment]
I added a style example to the previously mentioned cologne jug project.

**Comment by buzdin** [comment]
Thanks, was a bit worried due to disinformation in this issue.
