### ISSUE TITLE
Provide support for Spring Boot 1.5 in Vaadin-spring-boot : 2.0.0

### ISSUE THREAD

**Issue by darkwitch** [vaadin/spring#191]
Hi,

Please provide support for Spring Boot for vaadin-spring-boot 2.0.0.

**Comment by mstahv** [comment]
Hi,

Could you elaborate, what you mean with this ticket? The vaadin-spring-boot 2.0.0 should work perfectly with Spring Boot 1.5. I used it today in Vaadin 8 webinar with Spring Boot version 1.5.2

cheers,
matti

**Comment by darkwitch** [comment]
Hi Matti,

I actually saw the webinar and was wondering the same. So I did a little digging, and In turns out the problem is with peter's vaadin4spring extension, there's also a ticket on it (and a PR that fixes it)

https://github.com/peholmst/vaadin4spring/issues/302
https://github.com/peholmst/vaadin4spring/pull/300

**Comment by mstahv** [comment]
Ah, ok. Good to get this resolved. Now we just need to help @peholmst to to get the V8 and Spring Boot 1.5 compatible versions out of the oven. Lot of things to do for add-on developers.

**Comment by darkwitch** [comment]
I've actually helped a bit just now by creating a PR for this very thing https://github.com/peholmst/vaadin4spring/pull/303

**Comment by mstahv** [comment]
Awesome, big thanks!
