### ISSUE TITLE
Get a set of all discovered Views

### ISSUE THREAD

**Issue by ares242** [vaadin/spring#2]
Would be really useful to have a way to get a collection(Set) with the view names from the SpringViewProvider.

**Comment by GJRTimmer** [comment]
A view Can be part of multiple UI's. How do you envision such a collection(set) ?

- every view ?
- only the view which are part of a certain UI ?
- Get all the views registered within the view provider ?

How do you envisionto handle the secured views. The viewprovider returns ```null``` when a view is not allowed to be accessed so the navigator will not know anything about the view in your collection.

Can you please give more information, why you want a collection from the viewprovider ?

What is the goal you want to achieve ? Or what kind of functionality do you have in mind that would only 'be possible' or 'depend' on this requested functionality?

**Comment by ares242** [comment]
Well I am developing a dynamic role web application, so it would be useful  auto generate a menu with all the views that a user has access based on this role permissions to access a view.

**Comment by peholmst** [comment]
You might want to take a look at the SideBar in Vaadin4Spring (https://github.com/peholmst/vaadin4spring). It will receive some improvements in the near future. Feel free to add your feature requests there.

**Comment by fireflyc** [comment]
You can try the following code
```Java
final String[] viewBeanNames = applicationContext.getBeanNamesForAnnotation(SpringView.class);
        for (String beanName : viewBeanNames) {
            final Class<?> type = applicationContext.getType(beanName);
            if (View.class.isAssignableFrom(type)) {
                System.out.println(beanName);
            }
        }
```

**Comment by samie** [comment]
Created ticket in Vaadin for this one: https://dev.vaadin.com/ticket/18464

**Comment by hesara** [comment]
Tracked in Vaadin Trac.
