### ISSUE TITLE
Multiple instances of SpringViewDisplayRegistrationBeans

### ISSUE THREAD

**Issue by alump** [vaadin/spring#203]
Looks like when Vaadin Spring application is stressed, it can end up having multiple different instances of SpringViewDisplayRegistrationBeans, which then fails the application.

`org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.vaadin.spring.internal.SpringViewDisplayRegistrationBean' available: expected single matching bean but found 6: com.vaadin.spring.internal.SpringViewDisplayRegistrationBean#0,com.vaadin.spring.internal.SpringViewDisplayRegistrationBean#1,com.vaadin.spring.internal.SpringViewDisplayRegistrationBean#2,com.vaadin.spring.internal.SpringViewDisplayRegistrationBean#3,com.vaadin.spring.internal.SpringViewDisplayRegistrationBean#4,com.vaadin.spring.internal.SpringViewDisplayRegistrationBean#5`

And after this happens, the whole application is corrupted this way, it just keeps on adding new bean and then failing again. Only way to recover from this, is to restart the application.

Most likely some location where bean is asked is not synchronised correctly, and it causes two instances to be made.

**Comment by alump** [comment]
This only(?) happens when you use @SpringViewDisplay annotation, so you do not just use UI as navigator container. I have written simple app to reproduce the issue, and gatling test to be used to stress it. Please request it when you start to work with this issue.

**Comment by alump** [comment]
http://misc.siika.fi/springstress.zip - 65MB (most of it is Gatling)

**Comment by alump** [comment]
Most likely somehow related: https://github.com/vaadin/spring/issues/202https://github.com/vaadin/spring/issues/202

**Comment by alump** [comment]
OK, look like it's normal that multiple SpringViewDisplayRegistrationBean beans are created, so issue here is that given method receives all of them, not only the one it should in it's scope?

**Comment by alump** [comment]
org.springframework.beans.factory.support.resolveNamedBean(Class<T> requiredType, Object... args) is the one that breaks, after stress testing it will always found all the the bean (not the one it should) and so it throws NoUniqueBeanDefinitionException. Call chain is identical on success and failure cases.

**Comment by alump** [comment]
Kinda related, also Vaadin 7.7.8 & Vaadin-Spring 1.2.0 combination explodes, but differently, see https://gist.github.com/alump/3f26042f464acf9c4299d125d4928755

This is anyway smaller issue, as app is still usable after killing the Gatling. So please fix issue(s) on 8.0 & 2.0 series first.

**Comment by Legioth** [comment]
> Kinda related, also Vaadin 7.7.8 & Vaadin-Spring 1.2.0 combination explodes, but differently

This is a known issue that has been fixed in Vaadin Framework 8.0.0 (https://github.com/vaadin/framework/pull/7037) and further optimized in Vaadin Spring 2.0.0 (https://github.com/vaadin/spring/pull/168).

I'm not sure about backporting the fixes to the FW 7 series as the change from deterministic to indeterministic order for firing events might cause existing applications to break in some rare theoretical cases.

**Comment by hesara** [comment]
Fixed for 1.2.1 and 2.0.2
