### ISSUE TITLE
VaadinServiceInitListener

### ISSUE THREAD

**Issue by berndhopp** [vaadin/spring#213]
the VaadinServiceInitListener interface references Spring [here](https://github.com/vaadin/framework/blob/11ed9cd49088fa8e0a11530ff66a8600c7918550/server/src/main/java/com/vaadin/server/VaadinServiceInitListener.java#L33), but there seems to be no support for VaadinServiceInitListener so far.

**Comment by hesara** [comment]
Addressed by #218

**Comment by Legioth** [comment]
Won't work properly in cases that run any `add*` method on the service init method until https://github.com/vaadin/spring/pull/223 has also been merged.
