### ISSUE TITLE
How to write Tests/Integrationtests?

### ISSUE THREAD

**Issue by Petikoch** [vaadin/spring#220]
Hi there,

thanks for Vaadin and vaadin-spring, we really like it and use it (vaadin pro subscription).

I have a question regarding writing tests for spring-boot based vaadin applications. 

Of course, one could write "full blown" end-2-end acceptance tests using Selenium or Vaadin Testbench. But I think more in the direction of "spring boot integration tests using directly my Vaadin UI scoped beans".

I found no documentation about this in http://vaadin.github.io/spring-tutorial. 

I found some sample code like https://github.com/vaadin/spring/blob/999e4f204f6e7dbadf21a49dcaacd243f45e23a2/vaadin-spring/src/test/java/com/vaadin/spring/server/AbstractSpringUIProviderTest.java or https://github.com/vaadin/spring/blob/master/vaadin-spring-boot/src/test/java/com/vaadin/spring/boot/VaadinAutoConfigurationTest.java

Is "the way to go" to use the tests.jar from vaadin-spring and to build on e.g. AbstractSpringUIProviderTest?

Thanks for your feedback & best regards,
Peti

**Comment by elmot** [comment]
Hello,
I am not sure if those tests are really good starting points to write your tests. They are focused on testing  behavior of vaadin internal stuff and spring, and it looks like you need to write a lot of boilerplate code to test your application functionality on that level. IMO, it's better to restructure the application to follow MVP or MVC design patterns, with very thin V(iew) level, and then perform all the functionality testing at P(resenter) or C(ontroller) level.

**Comment by Petikoch** [comment]
Thanks @elmot for your comment. 

For my integration tests, I ended up using Vaadin Testbench together with Spring-Boot-Test and using the "MockBean"-Feature of Spring-Boot-Test to stub the external interfaces of the application. This is quite convenient, and I have good integration tests without being dependent on external systems.

The application is structured internally à la MVx (altough more like redux/cycle) and I have some good unit-tests there "on the controller level". 

Best regards,
Peti
