### ISSUE TITLE
vaadin-spring-boot : 2.1.0.beta2 maven issue

### ISSUE THREAD

**Issue by eepstein** [vaadin/spring#229]
Was a bad build pushed to maven repos?  
Referencing the latest pre-release (v 2.1.0.beta2) of vaadin-spring-boot gives:

`Could not resolve dependencies for project com.datavolo:fm-ui-vaadin:jar:0.1.0-SNAPSHOT: Failed to collect dependencies at com.vaadin:vaadin-spring-boot:jar:2.1.0.beta2: Failed to read artifact descriptor for com.vaadin:vaadin-spring-boot:jar:2.1.0.beta2: Could not find artifact com.vaadin:vaadin-spring-parent:pom:2.1.0.beta2 in vaadin-addons (http://maven.vaadin.com/vaadin-addons)`

Looks like the spring-parent pom for that version wasn't added to the vaadin-addons repo ?
And that version is not in the standard repo either:  https://mvnrepository.com/artifact/com.vaadin/vaadin-spring-parent

**Comment by Legioth** [comment]
Hi. Prereleases are in http://maven.vaadin.com/vaadin-prereleases/.

**Comment by eepstein** [comment]
Ah.  Of course.  Thanks!
