### ISSUE TITLE
vaadin-spring breaks @Configurable when used on a Component

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/spring#231]
Consider a class like this:

```
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Configurable;

@Configurable
public class MyWidget extends HorizontalLayout {

    @Autowired
    private FooService fooService;

    ....
}
```

Attempting to instantiate this class results in a `NoSuchBeanDefinitionException` being thrown.

Here's why:

```
public class SpringViewDisplayPostProcessor implements BeanPostProcessor,
        ApplicationContextAware, BeanFactoryAware {
    private ApplicationContext applicationContext;
    private ConfigurableListableBeanFactory beanFactory;

    private BeanNameGenerator beanNameGenerator = new DefaultBeanNameGenerator();

    @Override
    public Object postProcessAfterInitialization(final Object bean,
            String beanName) throws BeansException {
        final Class<?> clazz = bean.getClass();
        if (!Component.class.isAssignableFrom(clazz)
                && !ViewDisplay.class.isAssignableFrom(clazz)) {
            return bean;
        }
        if (beanFactory != null) {
            BeanDefinition beanDefinition = beanFactory
                    .getMergedBeanDefinition(beanName);
```

This class assumes that any `Component` encountered is defined in a bean factory. This is not the case for `@Configurable` beans, and so a `NoSuchBeanDefinitionException` is thrown.

Thinking about how to fix this, I think you could just catch and ignore the `NoSuchBeanDefinitionException`, skipping that section.

FYI, the code below that uses `Class.isAnnotationPresent()`. Instead, all Spring annotation finding should be done in such a way as to support [meta-annotations](https://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-meta-annotations). For example, using [AnnotatedElementUtils.findMergedAnnotation()](docs.spring.io/spring/docs/current/javadoc-api/?org/springframework/core/annotation/AnnotatedElementUtils.html). Feel free to create a separate issue for this that applies globally to the entire `vaadin-spring` codebase.

**Comment by m-emelchenkov** [comment]
What workaround do you use? I use the code from this page, item number 5: https://rioasmara.wordpress.com/2012/09/30/vaadin-and-spring-simple-autowire/

Is there any difference between `autowireBean` and `autowireBeanProperties` calls for this task?

**Comment by archiecobbs** [comment]
I'm working around this by finding other ways to get the required beans other than using `@Configurable`.

I'm not sure what the difference is between `autowireBean` and `autowireBeanProperties`.
