### ISSUE TITLE
Compatibility with Framework 8.2

### ISSUE THREAD

**Issue by heruan** [vaadin/spring#234]
I'm trying to use Vaadin Spring starter with Framework 8.2.0.alpha2 but I can't get my `@SpringUI` discovered. Is it supposed to be compatible with 8.2 yet?

**Comment by tsuoanttila** [comment]
@heruan I'll be testing some stuff around the Spring today when making some extra tests for it. We do have an integration test with the spring plugin, and it passed in the build, so the basic case should work. If I don't have any problems, I'll ping you again and let's figure out what goes wrong in your setup.

**Comment by tsuoanttila** [comment]
Spring add-on should work with 8.2.
