### ISSUE TITLE
Support for Vaadin 10

### ISSUE THREAD

**Issue by chvndb** [vaadin/spring#235]
The developer preview release of [Vaadin 10](https://vaadin.com/docs/v10/flow/Overview.html), has been officially announced.

Are there any plans in this project to provide integration with Spring for this new version of Vaadin?

**Comment by Legioth** [comment]
Explicit support for Spring and CDI as well as generic support for plugging any other DI framework will be core features of https://github.com/vaadin/flow instead of maintained as separate addons. 

Work on the Spring part is currently in progress.

**Comment by chvndb** [comment]
Awesome

**Comment by pleku** [comment]
@chvndb please see the Epic Issue https://app.zenhub.com/workspace/o/vaadin/flow/issues/2529 for details on progress.

**Comment by chvndb** [comment]
@pleku thanks !!
