### ISSUE TITLE
Memory leak in VaadinSessionScope

### ISSUE THREAD

**Issue by peholmst** [vaadin/spring#243]
This issue was discovered in Vaadin Spring version 2.0.1.

When a `VaadinSession` is closed, the `VaadinSessionScope` is not destroyed. This means it will remain a listener registered with the singleton `VaadinService`, preventing it and the `VaadinSession` itself from being GC:d.

The problem is in the `VaadinSessionScope.cleanupSession` method. The `SessionAwareBeanStore` instance is retrieved from the session using the `SessionAwareBeanStore` class, but it is actually stored using the `BeanStore` class. Thus, the returned bean store will always be null and `destroy()` will never be called.

**Comment by tsuoanttila** [comment]
Fix for this issue needs to be picked still to different versions where applicable. Already fixed in master.

**Comment by tsuoanttila** [comment]
Picked the fix for 2.0 and 2.1 branches as well.
