### ISSUE TITLE
Where to find documentation for Vaadin Spring 3.0.0 ?

### ISSUE THREAD

**Issue by Petikoch** [vaadin/spring#248]
Hi,

thanks for releasing Vaadin Spring 3.0.0.

I'm looking for the updated documentation showing the new features like @Secured and @PushStateNavigation, but can't find it. http://vaadin.github.io/spring-tutorial/ shows still 2.0.

Best regards,
Peti

**Comment by tsuoanttila** [comment]
Hi, because of CDI 3.0.0 and rush with 8.3.0 framework, we haven't had the time to update the tutorials. The basic usage of `@PushStateNavigation` is to add it to a `@SpringUI` and use the autowired Spring Navigator. The URLs should switch to paths instead of the hashbang `#!` uri fragments.

**Comment by Petikoch** [comment]
Thanks for your Feedback @tsuoanttila . 

Any plans when the updated documentation will be published?

**Comment by elmot** [comment]
@Petikoch , there is an example how to use it in our Bakery App example.
For instance,
https://github.com/vaadin/bakery-app-starter-fw8-spring/blob/2d35516166247ec016e8e4d3644dabcaec0050a3/src/main/java/com/vaadin/starter/bakery/ui/views/admin/AbstractCrudView.java#L57

**Comment by Petikoch** [comment]
Just to mention... http://vaadin.github.io/spring-tutorial/ shows still the 2.0 docs.
