### ISSUE TITLE
Multithreading issues

### ISSUE THREAD

**Issue by schupp** [vaadin/spring#25]
Hi. Just migrated from CDI to Spring and am now facing issues when using a UIScoped SpringView when changing the view state through a different thread. Am I missing something?

Here's my simple Demo code using spring-boot-starter-parent. Cheers, Ben

---
import javax.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.core.task.SimpleAsyncTaskExecutor;
import org.springframework.core.task.TaskExecutor;
import com.vaadin.annotations.Theme;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.VaadinRequest;
import com.vaadin.spring.annotation.SpringUI;
import com.vaadin.spring.annotation.SpringView;
import com.vaadin.spring.annotation.UIScope;
import com.vaadin.spring.navigator.SpringViewProvider;
import com.vaadin.ui.Label;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

@SpringBootApplication
public class SpringUIDemo {

    public static void main(String[] args) {
        SpringApplication.run(SpringUIDemo.class, args);
    }

    @Theme("valo")
    @SpringUI(path = "")
    public static class VaadinUI extends UI {

        @Autowired
        public void configureNavigator(SpringViewProvider viewProvider) {
            Navigator navigator = new Navigator(this, this);
            navigator.addProvider(viewProvider);
        }

        @Override
        protected void init(VaadinRequest request) {
        }
    }
    
    @UIScope
    @SpringView(name="")
    public static class MyView extends VerticalLayout implements View {
        
        TaskExecutor taskExecutor = new SimpleAsyncTaskExecutor();
        
        @PostConstruct
        public void init() {
            System.out.println("init view ");
            addComponent(new Label("Hi there!"));
        }
        
        @Override
        public void enter(ViewChangeEvent event) {
            System.out.println("enter view");
            addComponent(new Label("Hi there on enter!"));
            taskExecutor.execute(()->{
                getUI().access(() -> {
                    System.err.println("execute...");
                    addComponent(new Label("Hi there on enter async!"));
                });
            });
        }
    }
}

**Comment by peholmst** [comment]
What issues are you experiencing? It looks like the @Push annotation is missing from your UI, which would prevent the asynchronously added label from showing up until the next request.

**Comment by schupp** [comment]
I did miss something...
thanks and sorry to have bothered 
/Ben
