### ISSUE TITLE
Possibility of opening one view muliple times with its own beans

### ISSUE THREAD

**Issue by henrik-dvlpr** [vaadin/spring#251]
Greetings,

I want to open the `SpringView`s in a` TabSheet` as `ViewDisplay`. Each view will be opened in a separate new `Tab`. The problem is that the new view has the same bean as the first opened view.

Is it possible to open a view again that is already opened without destroying the old one?

E.g. I have opened `HomeView` on navigation state` home` with bean `homeView`. Now I want to open it again so it wants to open another tab with `HomeView`. This tab has to be related to navigationState `home-2` and bean` homeView2` as example. So it has its own bean and navigation state.

**Comment by TatuLund** [comment]
The answer is yes. Just use UIScope in the bean.
