### ISSUE TITLE
@PushStateNavigation issue when servlet not mapped to root path

### ISSUE THREAD

**Issue by kaffeebaum** [vaadin/spring#252]
I have trouble getting PushStateNavigation to work when the servlet is not mapped to the root path.

I have a web servlet `@WebServlet(value = {"/admin/*", "/VAADIN/*"})`
a Vaadin UI `@SpringUI // @SpringUI(path = "")`
and a View `@SpringView(name = "view1")`

which now can be accessed under
`http://localhost:8080/admin` or
`http://localhost:8080/admin#!view1`
respectively. Everything works fine.

If I now enable `@PushStateNavigation` I would expect the paths to change to
`http://localhost:8080/admin` and
`http://localhost:8080/admin/view1`
If I now navigate to view1, I get forwarded to `http://localhost:8080/view1`. Vaadin still shows the view, but if I go to the URL bar in den browser and hit return, I get a 404 error.

If I map the Vaadin UI to a specific path like `@SpringUI(path = "ui")`everything works again.

Am I doing something wrong? Or is this a bug?

I am using Vaadin 8.3.1 and Vaadin-Spring 3.0.0 on a Tomcat 7.

**Comment by TatuLund** [comment]
Is this related: https://github.com/vaadin/spring/issues/236 ?

**Comment by pontusbostrom** [comment]
It doesn't seem to be the same problem as #236, the problem is still there in version 3.0.0.
