### ISSUE TITLE
Theme loading issues with Flow beta6

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/spring#260]
@heruan commented on [Thu Apr 12 2018](https://github.com/vaadin/flow/issues/3876)

I'm experiencing issues with theme loading with Flow beta6, where Lumo is applied to some route targets but not to others even if they have the same root layout which is annotated with `@Theme(Lumo.class)`.

I'm trying hard to replicate this in a project I can share, but even with the same layout structure it does not replicate. I can just confirm that with Flow beta5 the theme loads correctly for all the route targets.

The layout structure is basically this:

```
@Theme(Lumo.class)
MainLayout extends VerticalLayout implements RouterLayout
 |
 |  @ParentLayout(MainLayout.class)
 |- SectionLayout extends VerticalLayout implements RouterLayout
     |
     |  @ParentLayout(SectionLayout.class)
     |- UserSection extends VerticalLayout implements RouterLayout
     |   |
     |   |  @Route(value = "users", layout = UserSection.class)
     |   |- UserList extends CustomFilterUserList extends ListView extends VerticalLayout
     |
     |  @ParentLayout(SectionLayout.class)
     |- SessionSection extends VerticalLayout implements RouterLayout
         |
         |  @Route(value = "sessions", layout = SessionSection.class)
         |- SessionList extends ListView extends VerticalLayout
```

where `SessionList` loads the theme correctly, but `UserList` does not.

No errors in server or browser console, just for the `UserList` not network request is done for files in `themes/lumo`, e.g. `vaadin-grid/themes/lumo/vaadin-grid.html`, but just e.g. `vaadin-grid/src/vaadin-grid.html`.

I'm open to suggestion on how to debug this!

---

@caalador commented on [Fri Apr 13 2018](https://github.com/vaadin/flow/issues/3876#issuecomment-381043107)

One starting point could be when navigating breakpointing on  in `UIInternals::updateTheme` and see that it gets the theme/step through and see at what point it gets wrong data.

The next would be loading, but as it work on one part it should work on the other also, but that would be from `UIInternals::getHtmlImportValue`

If updateTheme gets the wrong result then there might be a bug in the `RouteRegistry::getThemeFor`

---

@heruan commented on [Fri Apr 13 2018](https://github.com/vaadin/flow/issues/3876#issuecomment-381055285)

Thank you @caalador for the suggested breakpoint on `RouteRegistry::getThemeFor`, which clearly shows to issue: it is related to Spring, since the route target for which the theme isn't found is a Spring CGLIB proxy (since it has a `@Async` method).

So, the proxied class fails `targetRoutesMap.containsKey(navigationTarget)` in `RouteRegistry::getThemeFor` and the theme is not found.

I don't know how this is working in beta5, though (maybe it doesn't and I have dirty deps).

This is also related to #3843.

---

@caalador commented on [Fri Apr 13 2018](https://github.com/vaadin/flow/issues/3876#issuecomment-381063156)

In beta5 we still didn't have Lumo as default and the resolving was a bit different.

**Comment by pleku** [comment]
Is this issue still relevant ? @denis-anisimov @heruan ?
