### ISSUE TITLE
NPE on I18N Provider if using in custom components

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/spring#264]
@loefflefarn commented on [Tue Mar 13 2018](https://github.com/vaadin/flow/issues/3694)

Hello,

I'm using the Vaadin 10 Platform with Spring Boot 2.0.0 and their `MessageResources` for I18N. All works fine, but if I want to receive a `MessageResource` with `UI.getCurrent().getI18NProvider()` in a custom created component on Server side I get an NPE! My component is created so that it extends a `VerticalLayout`

My configured I18N Provider:
```java
import static java.util.Collections.singletonList;

import java.util.List;
import java.util.Locale;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.stereotype.Component;

import com.vaadin.flow.i18n.I18NProvider;

@Component
public class MessageSourceProvider implements I18NProvider
{
    private static final Locale DEFAULT_LOCALE = Locale.GERMANY;

    @Autowired
    private MessageSource messageSource;

    @Override
    public List<Locale> getProvidedLocales()
    {
        return singletonList(DEFAULT_LOCALE);
    }

    @Override
    public String getTranslation(String key, Object... params)
    {
        return messageSource.getMessage(key, params, key, DEFAULT_LOCALE);
    }

    @Override
    public String getTranslation(String key, Locale locale, Object... params)
    {
        return messageSource.getMessage(key, params, key, locale);
    }
}
```

Greetings!

**Comment by mimarko** [comment]
Any progress here ?

**Comment by pleku** [comment]
No progress yet, made sure this should be processed in near future in P2 queue as this is an old issue.

**Comment by denis-anisimov** [comment]
@loefflefarn 
1) It's not possible to call `UI.getCurrent().getI18NProvider()`  because there is no public `UI::getI18NProvider`  : it's private (at least in the latest release).
2) There is a reason why this method is private: `I18NProvider` is  SPI and not API. SPI should not be used as API.]
3) How do you get NPE ? I didn't get from the description what should I call to get an NPE.

Do you call `UI.getCurrent().getI18NProvider()`  and it produces an NPE ( even though there is not such method in `UI`, may be in older versions....) ?

If this call produces an NPE then it has no any relation to `I18NProvider`  and Spring.
`UI.getCurrent()`  can be `null`  if the component is not yet attached.

If I use `VaadinService.getCurrent().getInstantiator().getI18NProvider()`  then `I18NProvider`  is not `null`.

The correct way to get UI would be e.g. override `onAttach`:

```
    @Override
    protected void onAttach(AttachEvent attachEvent) {
      // here UI is available
    } 

```

If you have an issue which I was not able to detect here because of weak description then please provide exact steps to reproduce.

Please use skeleton project  https://github.com/vaadin/skeleton-starter-flow-spring to avoid unnecessary code to the issue can be localized.

**Comment by pleku** [comment]
Closing the issue due to inactivity and missing details.
