### ISSUE TITLE
Auto adding view to VaadinViewScope

### ISSUE THREAD

**Issue by bozzz91** [vaadin/spring#3]
Can an annotation @SpringView also add current marked view to VaadinViewScope?
Is this necessary to annotate view class with both @SpringView and @VaadinViewScope annotations?

make it like @SpringUI, which auto include ui into ui scope

**Comment by peholmst** [comment]
I think it is necessary, since you might not want all your views to be view scoped. Some might need to be prototype scoped and some might need to be UI scoped.

**Comment by KyleRogers** [comment]
But nevertheless View scope seems to be a good default. I haven't tested this but if you mark ```@SpringView``` as ```@VaadinViewScope``` one can override this "default" by applying a different scope at the class or bean declaration level, I think.

**Comment by peholmst** [comment]
It is worth considering.

**Comment by hesara** [comment]
I, too, believe having views view scoped by default is a good idea as long as overriding it is easy. We will look into this.

**Comment by peholmst** [comment]
I just added this to Vaadin4Spring and it works fine. Overriding the scope is just a matter of putting another scope annotation on the class.

**Comment by bozzz91** [comment]
Thx
