### ISSUE TITLE
Spring dependency injection doesn't work for fields in Vaadin 10

### ISSUE THREAD

**Issue by ilya-ershov** [vaadin/spring#327]
Permalink to forum topic: https://vaadin.com/forum/thread/17141549/17141550
Following example here https://vaadin.com/docs/v10/flow/spring/tutorial-spring-routing.html bean must be injected before contructor is called. It gets injected **only after** object is constructed.
There was a method initContent() for previous vaadin versions that could be used having all deps injected. Now its gone.. Is there alternative way other then using contructor parameters marked autowired?

**Comment by denis-anisimov** [comment]
The documentation is wrong.
We should fix it.
Autowired fields are not initialized before class is instantiated via its CTOR.
That's the way how Spring works and it doesn't relate to Vaadin.

You may use autowired field only in `@PostConstruct` methods or any method which is called after the class is instantiated.
Another option is to use `@Autowired` parameters in the CTOR.

**Comment by snicoll** [comment]
> That's the way how Spring works and it doesn't relate to Vaadin.

You can't really set the value of a `Field` without having an instance first so it has nothing to do with Spring either really. 

When you update the doc, please note that `@Autowired` is no longer required on single constructor.

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/flow-and-components-documentation #228](https://github.com/vaadin/flow-and-components-documentation/issues/228) via [**ZenHub**](https://www.zenhub.com/)
