### ISSUE TITLE
dispatcherServletRegistration duplicate bean definition Spring Boot 2.1.0.M4

### ISSUE THREAD

**Issue by steffen-harbich-cognitum** [vaadin/spring#354]
When I start my vaadin flow spring boot application the following error occurs:

> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> The bean 'dispatcherServletRegistration', defined in class path resource [com/vaadin/flow/spring/DispatcherServletRegistrationBeanConfig.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/DispatcherServletAutoConfiguration$DispatcherServletRegistrationConfiguration.class] and overriding is disabled.
> 
> Action:
> 
> Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

Spring boot version 2.1.0.M4, vaadin 11.0.0.beta3.

**Comment by snicoll** [comment]
Duplicate #331

**Comment by denis-anisimov** [comment]
Once this fixed this test should be enabled : 
https://github.com/vaadin/spring/issues/359

**Comment by elmot** [comment]
See discussion at https://github.com/spring-projects/spring-boot/issues/14014

**Comment by snicoll** [comment]
@elmot thanks for trying to help but #331 is really about stopping defining that bean at all (as it shouldn't be).

**Comment by caalador** [comment]
Closing this issue. The version of Spring Boot has been updated for later versions of Flow.
Open a new issue if the problem reappears.

**Comment by snicoll** [comment]
@caalador this is a duplicate issue, see https://github.com/vaadin/spring/issues/354#issuecomment-424373851
