### ISSUE TITLE
Revert PR #313 (8e2e673b30a62157c23f39879b25a4b819abecba commit)

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/spring#356]
8e2e673b30a62157c23f39879b25a4b819abecba commit introduces dependency to `vaadin-spring-starter` to all test modules.

The first question is: why ? ( @ZheSun88 )

Also it adds a UI component into `com.vaadin.flow.spring.scan.test.TestServletInitializer` ( a button is instantiated).

Again there is a question: what does it test?

It tests that `vaadin-core` is in the dependency (not really a proper way).
If only `vaadin-core` should be in the dep then why it adds `vaadin-spring-starter` ?

There should not be any UI components in the test modules.
All UI code is in the `spring-common`  module which contains all testing code for every testing module.
All dependency should go there.

And I don't think that `vaadin-core` should be in the dependency at all.
I don't see any reason why. This is test modules which doesn't have to have any dependency.
They don't really need this dependency.
If `vaadin-spring-starter`  needs to be tested as a dependency then there should be totally different module which does it.

The problem with `vaadin-spring-starter`  is: it depends on `vaadin-core` which comes from the platform whose version doesn't have to match to the vaadin version which is used in Spring tests.
That's why if you need this test it may not be a part of the existing (plain) Spring tests and should be totally different test (with its own testing module most likely).

**Comment by ZheSun88** [comment]
answer to the first question: https://github.com/vaadin/spring/issues/298 the original ticket is here.

to the second question, the button added there aims to verify that the user can use our components without adding separate dependencies. 

but after this change, there are some other discussions (cannot remember why or where or about what).

**Comment by denis-anisimov** [comment]
This ticket blocks https://reviewable.io/reviews/vaadin/spring/355

**Comment by denis-anisimov** [comment]
The reason why I don't like the test with `Button`  is: it doesn't test anything related to `vaadin-core` since I may add `Button`  component dependency explicitly without `vaadin-core`.
So the test is quite bad.

**Comment by ZheSun88** [comment]
yes, that is true. the proper test would be a project which contains the whole components set.
