### ISSUE TITLE
SpringViewProvider should be UIScoped

### ISSUE THREAD

**Issue by Artur-** [vaadin/spring#37]
`SpringViewProvider` is currently a singleton bean even though it ends up in each `VaadinSession`  and is thus serialized with the session. In practice after the fix for #35, it is not even a singleton bean but "most of the time maybe a singleton bean".

The view provider should really be UIScoped so that it tracks only the views for one view.

**Comment by hesara** [comment]
This will have an impact on how access denied (and after #22 error) views are configured. Considering this as a candidate for 1.1 as this relates to view management.
