### ISSUE TITLE
SpringServlet.config() does not set original.frontend.resources property

### ISSUE THREAD

**Issue by Milbor** [vaadin/spring#372]
vaadin-bom:11.0.1 = vaadin-spring:10.0.4, flow-server:1.0.5

Properties initialization in
https://github.com/vaadin/spring/blob/b5fb08aa96d53f0a0f913a931d6a2d54b6589031/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringServlet.java#L68

omits com.vaadin.flow.server.Constants.USE_ORIGINAL_FRONTEND_RESOURCES
https://github.com/vaadin/flow/blob/510da390aa922d416ee039a6c7da21f834f66e80/flow-server/src/main/java/com/vaadin/flow/server/Constants.java#L87

as a result com.vaadin.flow.function.DeploymentConfiguration.useCompiledFrontendResources()
https://github.com/vaadin/flow/blob/510da390aa922d416ee039a6c7da21f834f66e80/flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java#L283

always uses default value false for production mode and ignores Spring Boot application property vaadin.original.frontend.resources=true

**Comment by elmot** [comment]
Probably other parameters from _com.vaadin.flow.server.Constants_ should be transferred as well

**Comment by DonAscon** [comment]
This is preventing me from bringing an app in production, in combination with
[this bug in the vaadin-maven-plugin](https://github.com/vaadin/maven-plugin/issues/115)

**Comment by Andelous** [comment]
The changes made in #385 are not present in Vaadin 10.0.9... or are they?

In my POM I do have `vaadin.version` set to 10.0.9, but when I check the `SpringServlet` class file, it doesn't have the changes made in that pull request.

Just asking. Thanks in advance.

**Comment by Andelous** [comment]
The changes made in #385 are not present in Vaadin 10.0.9... or are they?

In my POM I do have `vaadin.version` set to 10.0.9, but when I check the `SpringServlet` class file, it doesn't have the changes made in that pull request.

Just asking. Thanks in advance.
