### ISSUE TITLE
vaadin-spring-boot-starter and vaadin flow-server-production

### ISSUE THREAD

**Issue by iatomic** [vaadin/spring#377]
spring-boot pulls in OLD version of flow-server.
I need newest flow-server-production so I did 

```
<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-spring-boot-starter</artifactId>
			<exclusions>
		        <exclusion>
		            <groupId>com.vaadin</groupId>
		            <artifactId>flow-server</artifactId>
		        </exclusion>
		       </exclusions>			
</dependency>
<dependency>
			 <groupId>com.vaadin</groupId>
			 <artifactId>flow-server-production-mode</artifactId>
</dependency>]
```

Now we get

ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project ROOT: Compilation failure: Compilation failure:
[ERROR] [2,44] package com.vaadin.flow.component.dependency does not exist

**Comment by iatomic** [comment]
would you post an example of what you mean?

**Comment by iatomic** [comment]
Here is the full pom

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.t</groupId>
	<artifactId>ROOT</artifactId>
	<name>T</name>
	<version>1</version>
	<packaging>war</packaging>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<!-- Dependencies -->
		<vaadin.version>11.0.1</vaadin.version>
		<component.version>1.1.0.beta1</component.version>
		<start-class>com.t.spring.Starter</start-class>
		<gwt.module.style>PRETTY</gwt.module.style>
	</properties>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.0.RELEASE</version>
	</parent>

	<pluginRepositories>
		<pluginRepository>
			<id>vaadin-prereleases</id>
			<url>https://maven.vaadin.com/vaadin-prereleases</url>
		</pluginRepository>
	</pluginRepositories>

	<repositories>
		<repository>
			<id>vaadin-prereleases</id>
			<url>https://maven.vaadin.com/vaadin-prereleases</url>
		</repository>

		<repository>
			<id>Vaadin Directory</id>
			<url>http://maven.vaadin.com/vaadin-addons</url>
		</repository>
	</repositories>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-bom</artifactId>
				<version>${vaadin.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>


		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-upload-flow</artifactId>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.11.3</version>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>com.vaadin</groupId>
					<artifactId>flow-server</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<optional>true</optional>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.vaadin.elmot</groupId>
			<artifactId>vaadin-geo-location-flow</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>org.hsqldb</groupId>
			<artifactId>hsqldb</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter</artifactId>
			<version>1.0.0.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>javax.mail-api</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.servlet.jsp.jstl</groupId>
			<artifactId>javax.servlet.jsp.jstl-api</artifactId>
			<version>1.2.2</version>
		</dependency>

		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jstl</artifactId>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>flow-server-production-mode</artifactId>
		</dependency>

	</dependencies>
	<build>

		<plugins>

			<plugin>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-maven-plugin</artifactId>
				<version>${vaadin.version}</version>

			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<image>my-image:${project.version}</image>
					<executable>true</executable>
				</configuration>
			</plugin>

			<plugin>
				<groupId>com.google.appengine</groupId>
				<artifactId>appengine-maven-plugin</artifactId>
				<version>1.9.63</version>
				<configuration>
					<enableJarClasses>false</enableJarClasses>
					<port>8080</port>
					<address>0.0.0.0</address>

				</configuration>
				<!-- <jvmFlags> -->
				<!-- <jvmFlag>-Xdebug</jvmFlag> -->
				<!-- <jvmFlag>-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n</jvmFlag> -->
				<!-- </jvmFlags> -->
			</plugin>
			<plugin>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-maven-plugin</artifactId>
				<version>${jetty.version}</version>
				<configuration>
					<webAppConfig>
						<resourceBases>
							<resourceBase>${transpilation.output}</resourceBase>
						</resourceBases>
					</webAppConfig>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>productionMode</id>
			<dependencies>
				<dependency>
					<groupId>com.vaadin</groupId>
					<artifactId>flow-server-production-mode</artifactId>
					<!-- <version>1.2.0</version> -->
					<!-- <scope>compile</scope> -->
				</dependency>
				<!-- <dependency> -->
				<!-- <groupId>com.vaadin</groupId> -->
				<!-- <artifactId>flow-server</artifactId> -->
				<!-- <version>1.2.0</version> -->
				<!-- </dependency> -->
				<dependency>
					<groupId>com.vaadin</groupId>
					<artifactId>flow-client</artifactId>
					<version>1.2.0</version>
				</dependency>

			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>com.vaadin</groupId>
						<artifactId>flow-maven-plugin</artifactId>
						<executions>
							<execution>
								<goals>
									<goal>copy-production-files</goal>
									<goal>package-for-production</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.eclipse.jetty</groupId>
						<artifactId>jetty-maven-plugin</artifactId>
						<version>${jetty.version}</version>
						<configuration>
							<webAppConfig>
								<resourceBases>
									<resourceBase>${transpilation.output}</resourceBase>
								</resourceBases>
							</webAppConfig>
						</configuration>
					</plugin>

				</plugins>
			</build>
		</profile>
	</profiles>
</project>

```

**Comment by iatomic** [comment]
java:[3,38] package com.vaadin.flow.component.page does not exist ETC ETC.......

**Comment by iatomic** [comment]
here is what it turns out.
The flow-server-production is NOTHING but a jar that has web fragment that contains

    <context-param>
        <param-name>productionMode</param-name> 
        <param-value>true</param-value>
    </context-param>

I DUMPED the entire flow-server-production jar and just added a paremeter.

A spectaculr piec of OVERengineering simple things. the entire page in vaadin on PRODUCTION mode
could probably be replaced with one comment.

ADD

    <context-param>
        <param-name>productionMode</param-name> 
        <param-value>true</param-value>
    </context-param>

to web.xml.

**Comment by iatomic** [comment]
well...we dcl checked...we have 
```

<context-param>
    <param-name>productionMode</param-name> 
    <param-value>true</param-value>
</context-param>
```

inside web.xml AND we have 				
```
<dependency>
					<groupId>com.vaadin</groupId>
					<artifactId>flow-server-production-mode</artifactId>
					<!-- <version>1.2.0</version> -->
					<!-- <scope>compile</scope> -->
</dependency>
```

and 
flow-server.jar
flow-server-production.jar(the one that only has web fragment.xml)

and it is still not working...

**Comment by iatomic** [comment]
We added 

	   @Override
	    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
	        return application.sources(Starter.class);
	    }

	    @Override
	    public void onStartup(ServletContext servletContext) throws ServletException {
	        servletContext.setInitParameter("productionMode", "true");
	        super.onStartup(servletContext);
	    }	

in addition to having explicit

<?xml version="1.0" encoding="utf-8"?>
<web-app version="3.1" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd">
    <context-param>
        <param-name>productionMode</param-name> 
        <param-value>true</param-value>      
    </context-param>
</web-app>


still not working...any ideas?

**Comment by elmot** [comment]
Production mode in V10+ is pretty different from V7 and V10.
It's not a runtime parameter anymore but app compilation setting
Try to add to your pom.xml
```xml
            <properties>
                <vaadin.productionMode>true</vaadin.productionMode>
            </properties>

            <dependencies>
                <dependency>
                    <groupId>com.vaadin</groupId>
                    <artifactId>flow-server-production-mode</artifactId>
                </dependency>
            </dependencies>

            <build>
...
                <plugins>
                    <plugin>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-maven-plugin</artifactId>
                        <version>${vaadin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>copy-production-files</goal>
                                    <goal>package-for-production</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
```

**Comment by iatomic** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.t</groupId>
	<artifactId>ROOT</artifactId>
	<name>T</name>
	<version>1</version>
	<packaging>war</packaging>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		
		<vaadin.version>11.0.1</vaadin.version>
		<component.version>1.1.0</component.version>
		<start-class>com.towriffic.spring.Starter</start-class>
		<gwt.module.style>PRETTY</gwt.module.style>
	</properties>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.0.RELEASE</version>
	</parent>

	<pluginRepositories>
		<pluginRepository>
			<id>vaadin-prereleases</id>
			<url>https://maven.vaadin.com/vaadin-prereleases</url>
		</pluginRepository>
	</pluginRepositories>

	<repositories>
		<repository>
			<id>vaadin-prereleases</id>
			<url>https://maven.vaadin.com/vaadin-prereleases</url>
		</repository>

		<repository>
			<id>Vaadin Directory</id>
			<url>http://maven.vaadin.com/vaadin-addons</url>
		</repository>
	</repositories>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-bom</artifactId>
				<version>${vaadin.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>


		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
				<exclusion>
			        <groupId>ch.qos.logback</groupId>
			        <artifactId>logback-classic</artifactId>
    			</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-upload-flow</artifactId>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.11.3</version>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-spring-boot-starter</artifactId>
			
			
			
			
			
			
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
				<exclusion>
			        <groupId>ch.qos.logback</groupId>
			        <artifactId>logback-classic</artifactId>
    			</exclusion>
			</exclusions>			
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<optional>true</optional>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
				<exclusion>
			        <groupId>ch.qos.logback</groupId>
			        <artifactId>logback-classic</artifactId>
    			</exclusion>				
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.vaadin.elmot</groupId>
			<artifactId>vaadin-geo-location-flow</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>org.hsqldb</groupId>
			<artifactId>hsqldb</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
				<exclusion>
					<groupId>ch.qos.logback</groupId>
					<artifactId>logback-classic</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter</artifactId>
			<version>1.0.0.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>javax.mail-api</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.servlet.jsp.jstl</groupId>
			<artifactId>javax.servlet.jsp.jstl-api</artifactId>
			<version>1.2.2</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jstl</artifactId>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>flow-server</artifactId>
			<version>1.2.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
				<exclusion>
			        <groupId>ch.qos.logback</groupId>
			        <artifactId>logback-classic</artifactId>
    			</exclusion>				
			</exclusions>			
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>flow-client</artifactId>
			<version>1.2.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
				<exclusion>
			        <groupId>ch.qos.logback</groupId>
			        <artifactId>logback-classic</artifactId>
    			</exclusion>				
			</exclusions>
		</dependency>
		<dependency>
		   <groupId>org.webjars.bowergithub.vaadin</groupId>
		   <artifactId>vaadin-icons</artifactId>
		   <version>4.2.1</version>
		</dependency>		
	</dependencies>
	<build>

		<plugins>

			<plugin>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-maven-plugin</artifactId>
				<version>${vaadin.version}</version>

			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<image>my-image:${project.version}</image>
					<executable>true</executable>
				</configuration>
			</plugin>

			<plugin>
				<groupId>com.google.appengine</groupId>
				<artifactId>appengine-maven-plugin</artifactId>
				<version>1.9.63</version>
				<configuration>
					<enableJarClasses>false</enableJarClasses>
					<port>8080</port>
					<address>0.0.0.0</address>

				</configuration>
				
				
				
				
			</plugin>
			<plugin>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-maven-plugin</artifactId>
				<version>${jetty.version}</version>
				<configuration>
					<webAppConfig>
						<resourceBases>
							<resourceBase>${transpilation.output}</resourceBase>
						</resourceBases>
					</webAppConfig>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>production</id>
			<dependencies>
				<dependency>
					<groupId>com.vaadin</groupId>
					<artifactId>flow-server-production-mode</artifactId>
				</dependency>
			</dependencies>
			<build>
				<plugins>
	              <plugin>
	                    <groupId>com.vaadin</groupId>
	                    <artifactId>vaadin-maven-plugin</artifactId>
	                    <version>${vaadin.version}</version>
	                    <executions>
	                        <execution>
	                            <goals>
	                                <goal>copy-production-files</goal>
	                                <goal>package-for-production</goal>
	                            </goals>
	                        </execution>
	                    </executions>
	                </plugin>
					<plugin>
						<groupId>org.eclipse.jetty</groupId>
						<artifactId>jetty-maven-plugin</artifactId>
						<version>${jetty.version}</version>
							<configuration>
								<webAppConfig>
									<resourceBases>
										<resourceBase> ${project.build.directory}/${project.build.finalName}</resourceBase>
									</resourceBases>
							      	<allowDuplicateFragmentNames>true</allowDuplicateFragmentNames>
  
								</webAppConfig>
							</configuration>
					</plugin>

				</plugins>
			</build>
		</profile>
	</profiles>
</project>

**Comment by iatomic** [comment]
good suggestions. 

I tried Vaadin beta 12 before...it did not work either. 
I will post back after trying your suggestions. much apreciated.

**Comment by iatomic** [comment]
===========================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
===========================================================
2018-11-08 16:40:57.739  WARN 6724 --- [nio-8080-exec-1] c.v.f.s.DefaultDeploymentConfiguration   :
===========================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
===========================================================
2018-11-08 16:40:57.750  WARN 6724 --- [nio-8080-exec-1] com.vaadin.flow.server.VaadinService     :
=================================================================
Vaadin depends on Atmosphere 2.4.30.vaadin1 but version 2.4.24.vaadin1 was found.
This might cause compatibility problems if push is used.
=================================================================

**Comment by iatomic** [comment]
===========================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
===========================================================
2018-11-08 16:40:57.739  WARN 6724 --- [nio-8080-exec-1] c.v.f.s.DefaultDeploymentConfiguration   :
===========================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
===========================================================
2018-11-08 16:40:57.750  WARN 6724 --- [nio-8080-exec-1] com.vaadin.flow.server.VaadinService     :
=================================================================
Vaadin depends on Atmosphere 2.4.30.vaadin1 but version 2.4.24.vaadin1 was found.
This might cause compatibility problems if push is used.
=================================================================

**Comment by pleku** [comment]
The production mode from the v12 version of the project base for spring boot works out fine.

For further help, please use our forum or gitter channel and only report issues to github, thanks.
