### ISSUE TITLE
Property to disable autoconfiguration

### ISSUE THREAD

**Issue by d1231** [vaadin/spring#379]
I think there is a need for a property to turn on/off the autoconfiguration:
https://github.com/vaadin/spring/blob/master/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java

Something like:
`@ConditionalOnProperty(prefix = "spring.vaadin", name = "enabled", matchIfMissing = true)`

I've seen it in other projects (like liquibase)

**Comment by snicoll** [comment]
For the record, the Spring Boot team recommends to disable the auto-configuration rather than resorting to `enabled` flags that duplicate the core feature. 

Could you please explain why you have Vaadin on the classpath and you don't want to use it?

**Comment by d1231** [comment]
Sorry. I didn't know that and I saw other projects using disabling via property so I thought it was good. 

My use case was to disable the configuration inside tests, I wanted to work without webenviorment and vaadin auto configuration needed that.

For some reason, the annotations way didn't work for me but in the end, I managed via properties (`spring.autoconfigure.exclude`) to disable.

Thank you.

**Comment by d1231** [comment]
I opened a new issue here:
https://github.com/vaadin/spring/issues/380

Hope it will help.
