### ISSUE TITLE
UIStore cleanup assumes the session is locked

### ISSUE THREAD

**Issue by Legioth** [vaadin/spring#383]
Based on https://stackoverflow.com/questions/53374996/vaadinsession-does-not-own-lock-during-destruction-leading-to-assertionerror, it seems like the cleanup logic in `UIStore` assumes it's run for a locked session. It seems like this is not the case when the servlet engine is shutting down.

**Comment by Vvalter** [comment]
This issue actually prevents me from properly implementing test automation in my current project.

Will this be fixed in the foreseeable future? I am not used to Vaadin code at all, but if someone could provide some pointers on how to fix this, I would be willing to create a pull request.

**Comment by Legioth** [comment]
> if someone could provide some pointers on how to fix this, I would be willing to create a pull request.

You probably only need to wrap the logic performed by `serviceDestroy` inside a `session.accessSynchronously` block: https://github.com/vaadin/spring/blob/3.0/vaadin-spring/src/main/java/com/vaadin/spring/internal/UIScopeImpl.java#L260

Then you'd also have to figure out how this could be automatically tested. With a little luck, it's already covered by a test, but the test isn't run with assertions enabled.

**Comment by knoobie** [comment]
A version with your fix was 9h ago released (3.2.0)

**Comment by TatuLund** [comment]
Closed by #390
