### ISSUE TITLE
Support for Spring Data for DataProvider

### ISSUE THREAD

**Issue by pleku** [vaadin/spring#388]
Add support for easily mapping from Spring data concepts like `Repository` and `Pageable` to `DataProvider`. See example in https://github.com/jojule/triplist/blob/master/src/main/java/fi/jole/triplog/workaround/PageableDataProvider.java

**Comment by heruan** [comment]
Beware that getting a `Page` will issue also a `count` query; better to use `Slice`.

**Comment by Legioth** [comment]
I'd recommend also looking at https://github.com/Artur-/spring-data-provider/tree/master/src/main/java/org/vaadin/artur/spring/dataprovider which has a fluent builder instead of requiring you to create a subclass and override abstract methods.

**Comment by pleku** [comment]
This issue has been fixed via  vaadin/flow#8557
