### ISSUE TITLE
Integrate live reload

### ISSUE THREAD

**Issue by Legioth** [vaadin/spring#397]
When using `spring-boot-devtools`, there's a feature that it can tell the browser that the page should be reloaded when the context has been reloaded. To use this feature, you need to install a browser extension that listens for those signals.

It's also possible to add a small JS snippet to the host page that sets up the same kind of listener. This is something that the Spring integration could do automatically by configuring a custom bootstrap listener if Spring Developer Tools are on the classpath and Vaadin's production mode is not enabled.

**Comment by pleku** [comment]
This has been done and is 🚢 in 14 and 17.
