### ISSUE TITLE
ClassCastException with AnnotationConfigWebApplicationContext

### ISSUE THREAD

**Issue by zlaval** [vaadin/spring#4]
I use Spring without any xml configuration.
When I annotate my Configuration class with @EnableVaadin I get the following error:

java.lang.ClassCastException: org.springframework.web.context.support.AnnotationConfigWebApplicationContext cannot be cast to org.springframework.beans.factory.support.BeanDefinitionRegistry
	at com.vaadin.spring.config.VaadinConfiguration.viewProvider(VaadinConfiguration.java:57)

I made a workaround, but maybe others want to use it similarly.

My initializer class (sort version) is the following:

public class WebContextInitializer implements WebApplicationInitializer {

  @Override
    public void onStartup(javax.servlet.ServletContext servletContext) throws ServletException {
        AnnotationConfigWebApplicationContext context = new AnnotationConfigWebApplicationContext();
        context.getEnvironment().setDefaultProfiles(Profiles.DEV);
        context.scan(AppKey.classPathScanPackage);
        servletContext.addListener(new ContextLoaderListener(context));
        registerServlet(servletContext);
    }

private void registerServlet(ServletContext servletContext) {
        ServletRegistration.Dynamic dispatcher = servletContext.addServlet("vaadin", SpringAwareVaadinServlet.class);
        dispatcher.setLoadOnStartup(1);
        dispatcher.addMapping("/*");
    }

}

And the method in VaadinConfiguration that throw the error:

@Bean
    SpringViewProvider viewProvider() {
        return new SpringViewProvider(applicationContext,
                (BeanDefinitionRegistry) applicationContext);
    }

**Comment by bozzz91** [comment]
i confirm this bug. it works only with spring boot app context.
but i tried to do something like this code, but error reproduces, coz AnnotationConfigWebApplicationContext is Still not instance of BeanDefinitionRegistry

**Comment by peholmst** [comment]
I provided a fix in https://github.com/peholmst/vaadin4spring. If it works, I'll make sure it is added to this code base as well.

**Comment by zlaval** [comment]
i thought vaadin-spring works with standard war and vaadin-spring-boot for springboot.
now i have a workaround, please notify me if you resolve (if resolve of course)

**Comment by hesara** [comment]
We have a fix for vaadin-spring under review - if you want to test it, see https://dev.vaadin.com/review/#/c/7565/ .

**Comment by zlaval** [comment]
thx you

**Comment by hesara** [comment]
After some testing, integrated the change to vaadin-spring

**Comment by zlaval** [comment]
thanks, im going to try at night, after work

**Comment by zlaval** [comment]
i tried it, it works properly
