### ISSUE TITLE
Bump Spring add-on versions

### ISSUE THREAD

**Issue by pleku** [vaadin/spring#422]
- [x] Take the current `master` branch and push it to a `11.1` version branch
- [ ] Add the gson library as a dependency because build will fail without it, a workaround for https://github.com/vaadin/flow/issues/5426
- [x] Make a PR to `master` to use Flow `2.0-SNAPSHOT` and bump spring add-on version to `12.0-SNAPSHOT`

Releasing an alpha of the add-on will be on another ticket, to be based on Flow `2.0.0.alpha4`.

**Comment by SomeoneToIgnore** [comment]
No Gson library needed due to https://github.com/vaadin/flow/pull/5460
