### ISSUE TITLE
Npm mode is not detected in Spring IT tests

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/spring#433]
See IT test run https://bender.vaadin.com/viewLog.html?buildId=57757&buildTypeId=Flow_AddOns_FlowSpring

Tests fail due because the Flow starts in Bower mode even though we have all the resources and annotations done for the npm mode.

Currently a stub that enforces the tests run with `-Dvaadin.bowerMode=false` is done, but the underlying issue needs to be fixed.

**Comment by mehdi-vaadin** [comment]
All tests are green now. So, I assume this issue can be closed.
