### ISSUE TITLE
CustomResourceLoader parser works wrong when run as a .jar

### ISSUE THREAD

**Issue by caalador** [vaadin/spring#480]
When running a spring boot application as a jar using `java -jar target\my-starter-project-2.0-SNAPSHOT.jar`  the parsing of the file for `CustomResourceLoader` fails making the application fail to start.

This is because the loader expects there to be only one instance of `.jar!/` in the resource path, but when running a jar the path will start with the base jar e.g.  `file:/C:/tmp/my-starter-project/target/my-starter-project-2.0-SNAPSHOT.jar!/BOOT-INF/lib/flow-server-2.0.8.jar!/com/vaadin/` instead of for instance `file:/C:/~/.m2/repository/com/vaadin/vaadin-button-flow/2.0.0/vaadin-button-flow-2.0.0.jar!/com/vaadin/` where we only have a single jar!/

**Comment by mshabarov** [comment]
@caalador is this problem still being observed? I run `skeleton-starter-flow-spring` via `java -jar target/spring-skeleton-2.0-SNAPSHOT.jar` and app is started successfully.

**Comment by caalador** [comment]
Fixed in Flow issues 6685 and 7072
