### ISSUE TITLE
Performance issues when using vaadin-spring with npm

### ISSUE THREAD

**Issue by appreciated** [vaadin/spring#492]
Since I switched my [addon collection](https://github.com/appreciated/appreciated-collection) to Vaadin 14 Spring (running on heroku), I am experiencing unreasonable high response times (20+ seconds) and high memory consumption when using Spring boot. I haven't tried yet to see if the issue does not occur jetty.

![grafik](https://user-images.githubusercontent.com/1729845/64997605-8b6e1780-d8e1-11e9-8b38-16254832a357.png)

My run params: `-Dvaadin.productionMode=true -Xmx280m -Xss256k` 

The heroku application has a limited memory of 512MB. Reducing the Xmx brought the response time from ~30 Seconds down to 20 Seconds. 

Running this locally brings this down to ~15ish seconds it seems to depend a lot on the content that is being loaded.

Any idea what could cause the issue?

**Comment by mvysny** [comment]
From the screenshot I judge that the app simply uses all of available memory: the memory usage is constantly around 256MB and the GC times are simply huge. The response times could be bogged down by GC desperately trying to free up some memory.

It's great that you've been able to reproduce it locally - local env is faster because it's not virtualized. You'll need to memory-profile it - there could be a memory leak, either in your app, or in Vaadin, or the app simply needs more memory.

You can try getting rid of Spring and using pure Jetty, that could bring down the memory usage a bit (or at least could make memory profiling easier): https://github.com/mvysny/vaadin14-embedded-jetty

**Comment by mvysny** [comment]
Also please make sure that you're actually running in production mode on Heroku. If not, the webpack process started in development mode could eat a lot of memory. The `-Dvaadin.productionMode=true` should be enough though...

**Comment by appreciated** [comment]
@mvysny thank you very much for your tips. I switched now my application to use jetty instead of spring-boot and my memory consumption dropped immediately the application is now **much** faster 🎉. 

I am convinced that my memory issues are definitely related with vaadin-spring. 
Possibly in combination with an excessive use of Components using of `@JsModule` and/or `@NpmPackage` and/or `@Container`. 
As I've learned vaadin-spring scans Components differently than the the war version. Ppossibly there is memory leak/maybe when resolving the dependencies of Components, or maybe it is done too often. 
Also using the new vaadin-spring `12.0.6` did not seem to improve the situation. 
But no clarity here I will try to get a minimal example working.

**Comment by denis-anisimov** [comment]
>Possibly in combination with an excessive use of Components using of @JsModule and/or @NpmPackage and/or @Container.

I would like to clarify this.
`JsModule` and `NpmPackage` annotations are scanned _only_ once at startup time.
As I understand you have problem during application work (response time).
In that case I don't see how `JsModule` and `NpmPackage` annotations may affect this anyhow.

I'm not sure whether this is NPM related issue at all.

>As I've learned vaadin-spring scans Components differently than the the war version. 

Yes, but again: that happens one time only.

>Possibly there is a memory leak/maybe when resolving the dependencies of Components, or maybe it is done too often.

Memory licks during the scanning: quite unlikely.
Done too often: it's done once. So, no.

Question: are we talking about dev mode or production mode ?
You mentioned heroku, so I guess it's production mode.
But with production mode there is no any scanning at all during runtime.
Everything is built once with maven plugin. 

If you are running dev mode then please try production mode and see whether you have the same issue.

In the end, yes, please make minimal working example.

**Comment by appreciated** [comment]
Hi @denis-anisimov, 
as being said, these are just some assumptions, nothing concrete here.

> I would like to clarify this.
> JsModule and NpmPackage annotations are scanned only once at startup time.

I see! Thank you for clarifying this.

> Question: are we talking about dev mode or production mode ?

If this is enough, then yes:
> My run params: -Dvaadin.productionMode=true -Xmx280m -Xss256k

> In the end, yes, please make minimal working example.

I'm currently very short on time due to my master-thesis. I will try my best to create one soon.

**Comment by denis-anisimov** [comment]
OK, it's production mode.
So all the assumptions here are not correct.
During production mode no any scanning is done.

So there is totally different cause of this behavior.
And we will need info to be able to reproduce and understand the issue.

>I'm currently very short on time due to my master-thesis. I will try my best to create one soon.

Sure, take your time.
Let us know when you have info that we can use to identify the problem once you have it.

**Comment by appreciated** [comment]
@denis-anisimov I just tried my demo application which had response time issues:
> Running this locally brings this down to ~15ish seconds it seems to depend a lot on the content that is being loaded.

With `14.0.12`, the times went down from ~15ish seconds to ~2ish so it seems that this issue has already been fixed between 14.0.6 and 14.0.12.
