### ISSUE TITLE
Usage of Vaadin4Spring EventBus addon doesn't coexist with Vaadin Spring Boot: No views and no UIs found

### ISSUE THREAD

**Issue by Tonix-Tuft** [vaadin/spring#5]
Hi,

I would like to ask, does the Vaadin Spring Boot addon provides some functionality to integrate the Vaadin4Spring EventBus addon? If I use both Vaadin Spring Boot and Vaadin4Spring with the EventBus framework no views annotated with `@SpringView` are found by the `SpringViewProvider` and even no `@SpringUI("")` UI is found when I open the application in the browser.

**Comment by peholmst** [comment]
Vaadin4Spring has not yet been migrated to use the official Spring add-on. This will happen as soon as the official add-on reaches the beta phase. Then, all features implemented by the official add-on will be removed from Vaadin4Spring.

**Comment by Tonix-Tuft** [comment]
Understood, will wait! Thank for the work you've done!

**Comment by zkendall** [comment]
Have you tried since then Tonix-Tuft. I'm using The Vaading-Spring addon as well as spring-vaadin-eventbus 0.0.5.

**Comment by Tonix-Tuft** [comment]
No I haven't tried it yet. But I was already able to use the EventBus with Vaadin-Spring at that time, when the official release was not officially released yet, using the `feature/official_spring_support` branch which now, as I saw, is no longer available (here is a post of a guy that suggested me the workaround at that time -> http://stackoverflow.com/questions/28798110/how-to-use-the-new-vaadin-spring-boot-addon-together-with-vaadin4spring-eventbus#answer-28800167). Of course now this doesn't work anymore.

**Comment by peholmst** [comment]
The official spring support branch has been merged into the master branch. There should not be any problems with Vaadin Spring, Vaadin Spring Boot and Vaadin4Spring at this time.
