### ISSUE TITLE
Flag reverting pnpm is broken

### ISSUE THREAD

**Issue by pleku** [vaadin/spring#538]
For 14.2, when writing the following to `application.properties`, it should switch between `pnpm` and `npm`:
```
vaadin.disable.pnpm=true
```
But this not happen, project is always run with `pnpm`

NOTE: this will be changed to `vaadin.pnpm.enable` after vaadin/flow#7398

**Comment by denis-anisimov** [comment]
This flag is not recognized as a property at all I believe.
It needs modification in the Spring plugin to extend the properties.
