### ISSUE TITLE
@VaadinSessionScope could not be autowired in beans of other scope

### ISSUE THREAD

**Issue by t0920008899** [vaadin/spring#551]
When autowiring the class annotated with @VaadinSessionScope in beans with application scope came up with error messages. VaadinSesssionScope is not able to act like Spring session-scoped bean with has proxyMode definition to allow for use in the application-scoped bean.

**Comment by TatuLund** [comment]
Normally it is not possible to autowire / inject Bean of smaller scope, like @VaadinSessionScope to a @ApplicationScope. It works in opposite direction, i.e. you can share Beans of larger scope like @ApplicationScope services in Beans of smaller scope, like @VaadinSessionScope, etc.

**Comment by t0920008899** [comment]
> Normally it is not possible to autowire / inject Bean of smaller scope, like @VaadinSessionScope to a @ApplicationScope. It works in opposite direction, i.e. you can share Beans of larger scope like @ApplicationScope services in Beans of smaller scope, like @VaadinSessionScope, etc.

My scenario is to update a session-scoped object in custom AuthenticationProvider in Springboot when user logged in successfully to carry some info. That custom AuthenticationProvider was annotated as Service, and that session-scoped object could not get autowired. For now, I defined using Spring's session scope with proxyMode attribute.

**Comment by TatuLund** [comment]
For me this sounds that you need to autowire your AuthenticationProvider to your session-scoped object, so that the session-scoped object can use the information from the authentication provider it needs.

**Comment by denis-anisimov** [comment]
Could you please provide a source code which we can use to see the behavior which is wrong in your opinion ?
This code is required to be able to understand that we fixing exactly what you referring to and not something we thing you referring to.

**Comment by pleku** [comment]
I'm closing this issue as there has not been a response from the author in several weeks.

If this is still a problem, please create a new issue with means to reproduce the bug.
