### ISSUE TITLE
Allow DependencyInjection for AppShellConfigurator

### ISSUE THREAD

**Issue by Firestorm87** [vaadin/spring#564]
With Flow 3.0 the new AppShellConfigurator only allows the default constructor, so that global services (like an GoogleAnalyticsService) could not be used for the configuration of the AppShell.

**Comment by Legioth** [comment]
Expressed in Vaadin terminology, this means that the app shell instance should be created using  `Instantiator`.

**Comment by Firestorm87** [comment]
Thank you 👍
