### ISSUE TITLE
Slow classpath scanning for Spring Boot application when running Application.java

### ISSUE THREAD

**Issue by joheriks** [vaadin/spring#571]
To reproduce:
1. Activate Java 8 in IDE
2. Download [spring starter](https://github.com/vaadin/skeleton-starter-flow-spring)
3. Run `Application.java` 
4. Note that classpath scanning takes a long time, e.g.:
```Search for subclasses and classes with annotations took 5744 ms```
5. Stop the application
6. Run instead the maven goal `spring-boot:run`
7. Note that classpath scanning is faster,e.g.:
```Search for subclasses and classes with annotations took 2656 ms```
8. Activate Java 13 in IDE
9. Note that when running the application in either way the classpath scanning takes the same time:
```Search for subclasses and classes with annotations took 1747 ms```
```Search for subclasses and classes with annotations took 1809 ms```

Expectation: There is no major discrepancy between classpath scanning when running `Application.java` compared to using Maven. As a developer I prefer the former as it enables IDE debugging.

Versions:
- Vaadin 14.2 (or newer)
- IntelliJ IDEA (Ultimate 2019.13)
- Java 8 (jdk1.8.0_202.jdk) 
- Java 13 (openjdk-13.0.2.jdk)

**Comment by denis-anisimov** [comment]
I cannot reproduce Java 8 behavior.
Running via Spring boot maven plugin is even worse for me:
Search for subclasses and classes with annotations took 3618 ms - Java main class via IDE
Search for subclasses and classes with annotations took 4150 ms - via maven plugin

I'm using Eclipse. May be related to IntelliJ IDEA ?
May be someone else should take a look to this.

**Comment by miclefebvre** [comment]
Any updates about this issue ? 

I'm experiencing the same thing and it's really painful. Any workaround ? 

2020-05-22 10:21:34.354  INFO 18544 --- [  restartedMain] c.v.f.s.VaadinServletContextInitializer  : Search for subclasses and classes with annotations took 47 seconds

IntelliJ 2020.1
Java 8
Vaadin 14.2.0

**Comment by miclefebvre** [comment]
Setting vaadin.whitelisted-packages properties pointing on the main package of my application fixed the issue.

If not set, Vaadin seems to scan all packages of all dependencies of the project and it takes a lot of time to do it.

**Comment by johannest** [comment]
We have a biggish application and trying to switch from v14 compatibility mode to npm-mode (NPM-mode 14.2.1 flow-maven-plugin 2.2.2), but server startup times in dev mode went from ~80s to ~320s. 

The most significant chunck of time is spent into w.spring.VaadinServletContextInitializer : Search for subclasses and classes with annotations took 205 seconds

**Comment by joheriks** [comment]
Result from investigation: the discrepancy in startup time between `spring-boot:run` and running `Application::main` directly  is due to largely different number of classes on classpath: when running the class from IntelliJ with Oracle Java 8, number of classes processed by Spring's `ClassPathScanningCandidateComponentProvider::findCandidateComponents` were around 40k (compared to 15k when running via Maven), mostly JDK classes. The above PR extends the list of skipped packages with `java` and `oracle` prefixed ones.

Note that this does not affect performance in large projects with many dependencies, since by default all these are scanned. Setting the packages to be scanned exclusively via `vaadin.whitelisted-packages`, as described above, is the solution there.
