### ISSUE TITLE
vaadin-spring-boot-starter 15.0.5 projects do not start with Spring Boot 2.3

### ISSUE THREAD

**Issue by Artur-** [vaadin/spring#606]
Spring Boot 2.3 has removed the validation implementation `spring-boot-starter-validation` from `spring-boot-starter-web`, see https://github.com/spring-projects/spring-boot/issues/19550. If you take the Spring starter today and upgrade to 2.3.0.M3, startup fails with
```
***************************
APPLICATION FAILED TO START
***************************

Description:

The Bean Validation API is on the classpath but no implementation could be found

Action:

Add an implementation, such as Hibernate Validator, to the classpath
```

**Comment by Artur-** [comment]
Adding
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
```
works around the problem

**Comment by snicoll** [comment]
Is the validation piece mandatory in Vaadin?

**Comment by Legioth** [comment]
The validation API is only used for one optional feature, namely `BeanValidationBinder` which is a custom version of the generic `Binder`. We should have our own logic there that tries to find an implementation only if you're using that particular class and even in that case it should fail with our own custom error message if no implementation is available.

**Comment by Legioth** [comment]
@vlukashov Did we also add something related to validation for endpoints in Vaadin 15, or is everything there still pending the full form binding functionality that is being implemented right now?

**Comment by denis-anisimov** [comment]
I don't understand which functionality prints the error.
Bean validation impl is needed only when you are using `BeanValidationBinder` explicitly.
And it prints the error if you don't have the impl.

Otherwise the bean validation impl is not needed and never checked.

So it looks like it's not code in Flow or Spring add-on which prints the error message and fails the app to start.

It looks like this is Spring itself which prints the message.
So it's the matter of the generated project configuration : it needs to be changed somehow so Spring doesn't complain.

And to be able to understand the reason exactly I would like to see exact steps to reproduce which I'm lacking from the description.

**Comment by Artur-** [comment]
https://github.com/vaadin/skeleton-starter-flow-spring/tree/spring-boot-23

**Comment by Artur-** [comment]
Running 
```
mvn -X
```

shows the reason as
```
2020-04-24 11:47:12.642  WARN 43740 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.vaadin.flow.server.connect.VaadinConnectController': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.vaadin.flow.server.connect.VaadinConnectController]: Constructor threw exception; nested exception is javax.validation.NoProviderFoundException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
```

**Comment by denis-anisimov** [comment]
Alright, thanks.

```
 private final Validator validator = Validation
            .buildDefaultValidatorFactory().getValidator();
```

in the class `VaadinConnectController`.

**Comment by vlukashov** [comment]
May be caused by https://github.com/vaadin/flow/pull/8095.
ping @haijian-vaadin
