### ISSUE TITLE
Consider removing unnecessary version for hibernate validator 

### ISSUE THREAD

**Issue by snicoll** [vaadin/spring#632]
I made [a comment on the PR](https://github.com/vaadin/spring/pull/608#issuecomment-619935423) that changed this and it was either overlooked or ignored.

The [version for Hibernate validator](https://github.com/vaadin/spring/blob/8bf23ee5b01548c02374b0f12d2649bbb8b25252/vaadin-spring/pom.xml#L89) is useless and dangerous as this project potentially compiles and test against a different version of Hibernate Validator than  what apps are going to use. Please consider removing it as the rest of the dependencies that are already managed.

**Comment by mshabarov** [comment]
Hello @snicoll , thank you for ticket! Do you propose to remove the version of `hibernate-validator` so as to use this transitive version from [flow-server](https://github.com/vaadin/flow/blob/dd8e41bd390c2ac413454203ef65f580ef59a956/pom.xml#L85)?

**Comment by snicoll** [comment]
> Do you propose to remove the version of hibernate-validator so as to use this transitive version from flow-server?

Nope. This project [import Spring Boot's dependency management](https://github.com/vaadin/spring/blob/8bf23ee5b01548c02374b0f12d2649bbb8b25252/pom.xml#L61-L67) to make sure that the bits are compiled and tested with the same version as anyone else using that Spring Boot version.

Adding an explicit version for hibernate validator prevents that. I don't see a reason why you should build against that particular version anyway.

**Comment by mshabarov** [comment]
Thank you, @snicoll for clarifications! That's a good point.
