### ISSUE TITLE
Spring boot configuration vaadin.pnpm-enabled

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/spring#634]
In Vaadin 14.3.0.alpha1, when I tried to update Spring configuration file to switch to PNPM, by default IntelliJ suggests this:
vaadin.pnpm-enabled=true/false

Which is not working.

The documentation says:
For a Spring Boot based project, you can put vaadin.pnpm.enable = true into the application.properties files

Which is the right value, any idea why this configuration is found?

**Comment by caalador** [comment]
the property is `pnpm.enable` so it means in the application.properties it should be `vaadin.pnpm.enable`

**Comment by jcgueriaud1** [comment]
In this file  https://github.com/vaadin/spring/blob/master/vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
 the property is pnpmEnabled. That's exactly what IntelliJ found and suggest in the autocomplete.

**Comment by jcgueriaud1** [comment]
I think the problem is related to this PR: https://github.com/vaadin/spring/pull/572

**Comment by pleku** [comment]
@denis-anisimov what do you think, should we just revert the contribution that adds it for autoconfiguration since it suggests the wrong format ?

**Comment by denis-anisimov** [comment]
Yes, let's remove it.

I can't find how to use `ConfigurationProperties` with properties which have dots in the name.

**Comment by snicoll** [comment]
> I can't find how to use ConfigurationProperties with properties which have dots in the name.

What do you mean by that? 

> , should we just revert the contribution that adds it for autoconfiguration since it suggests the wrong format ?

What wrong format is that? What is the difference between `asyncSupported` and `pnpmEnabled` in the very same class?

This should provide the following properties:

* `vaadin.async-supported` (default to `true`)
* `vaadin.pnpm-enabled` (default to `false`)

I don't really understand the problem. There is a typo in the description of the `pnpmEnabled` property.

**Comment by jcgueriaud1** [comment]
The correct property is vaadin.pnpm.enable.

The file VaadinConfigurationProperties.java contains vaadin.pnpm-enabled and has been made to provide IDE assistance. This property is not used.

The other properties in this java file are used (I think).

Perhaps there is a different way to provide IDE assistance like manually update or create META-INF/spring-configuration-metadata.json for all the vaadin configuration properties.
vaadin.pnpm.enable
vaadin.productionMode ....

That will be really useful.

**Comment by snicoll** [comment]
If that's a typo, then the property should be renamed to `pnpmEnable` as well as the accessor methods (getter/setter). If the property is not used, I don't really understand why it's there.

> Perhaps there is a different way to provide IDE assistance like manually update or create META-INF/spring-configuration-metadata.json 

This is covered [in the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-configuration-metadata.html#configuration-metadata-additional-metadata). Here is [an example of a property that is not used in code](https://github.com/spring-projects/spring-boot/blob/b72a43859abc38cfbe1cc400996bcc4540929229/spring-boot-project/spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L342-L347) but for which we want content assistance as something checks its presence programmatically.

**Comment by denis-anisimov** [comment]
There is no any typo.
The property name is `pnpm.enable`.
It's extremely weird for me to rename the property which has no any relation to Spring just because Spring is not able to handle property name with a dot.

But let's not go into this discussion.
This is about another topic and we should just revert an issue which has been mistakenly introduced.

**Comment by denis-anisimov** [comment]
Another way could be translate Spring property name`pnpm-enabled` property ( or `pnpm-enable` ) to the Flow `pnpm.enable` property.

But I don't really like this solution since the property names will be different in Spring and non Spring. This is confusing.

**Comment by jcgueriaud1** [comment]
I think the solution is to remove this property from the Java file because it has only been added for IDE assistance and create a file  META-INF/additional-spring-configuration-metadata.json that contains the vaadin properties to enable IDE assistance.
For example this:
```
{
  "properties": [
    {
      "name": "vaadin.pnpm.enable",
      "type": "java.lang.Boolean",
      "description": "this flag can be used to enable pnpm instead of npm for resolving and downloading frontend dependencies",
      "defaultValue": false
    },
....
}
```
And also all the vaadin properties documented here:
https://vaadin.com/docs/v14/flow/advanced/tutorial-all-vaadin-properties.html

**Comment by denis-anisimov** [comment]
By the way : `pnpmEnabled`  is not a mistake.
It reflects the name of the property which it had initially.
We have renamed it to `pnpm.enable` and forgot to rename it in Spring.

**Comment by jcgueriaud1** [comment]
At least the PR that adds the code to autocomplete the property says:
`This is useful so that IntelliJ and other editors that support Spring Boot configuration files automatically recognize the vaadin.pnpm.enable (boolean) configuration property.`
But the code in the PR add autocomplete for property `vaadin.pnpmEnabled`.

And the java code is set (VaadinConfigurationProperties#setPnpmEnabled) but never read by vaadin-spring (VaadinConfigurationProperties#isPnpmEnabled).

I've updated the branch in the PR. I can remove the unrelated documented properties to focus only on vaadin.pnpm.enable.
