### ISSUE TITLE
Requests not running through web filters

### ISSUE THREAD

**Issue by heruan** [vaadin/spring#638]
After updating to V16, the filters set in `WebSecurityConfigurerAdapter#configure` are no longer invoked for requests managed by the Vaadin servlet. Is this expected? With V14 they are invoked correctly.

**Comment by pleku** [comment]
My guess would be that this is related to the client driven UI changes (TS views).

**Comment by heruan** [comment]
Thanks Pekka! Is this expected? Basically all Spring-based security isn't working. Do I need special settings/configuration to get the filters back in line?

**Comment by heruan** [comment]
Notice that I'm not using TS views, I've just updated the platform.

**Comment by vlukashov** [comment]
This sounds more like a bug than an intentional change. Would it be possible for you to attach a small project that shows the issue? That would help investigate and fix it!

**Comment by heruan** [comment]
Thank you Viktor, I've tried to add a filter to the Spring starter and it works. I need to investigate why they stopped working on my app after updating to V16, strange thing is: the adapter is invoked correctly at boot (so the filter is added) but it doesn't get called.

**Comment by heruan** [comment]
Sorry for the fuss, it was an issue of Eclipse 2020-06 which was including test-scoped dependencies.
