### ISSUE TITLE
Alternative names for `blacklisted-packages` and `whitelisted-packages`

### ISSUE THREAD

**Issue by joheriks** [vaadin/spring#645]
Property `blacklisted-packages` is currently used to specifically exclude packages from scanning for annotations etc., while `whitelisted-packages` is used to exclusively include packages in scanning. These names do not convey the semantics of the properties very well, and there are indications that these terms are being perceived as increasingly dated by the developer community. 

If done, documentation should be updated and support previous names as well for backwards compatibility. Other property naming related issues that may be relevant to consider at the same time are #634 and #637.

**Comment by jouni** [comment]
Suggested new property names:

- `blacklisted-packages` → `blocked-packages`
- `whitelisted-packages` → `allowed-packages`

**Comment by jouni** [comment]
I noticed that the `whitelisted-packages` property is used in a new project I created using our CLI tool, at least for a new Hilla project. We should update that once this change has been released.
