### ISSUE TITLE
make ui class configurable when using spring integration

### ISSUE THREAD

**Issue by sniffertine** [vaadin/spring#649]
As spring takes over the configuration of the spring vaadin servlet, you cannot easily define you own UI class as you would when using `com.vaadin.flow.server.VaadinServletConfiguration#ui`. Would be nice to have this available. 
One use case is to override `onDetach` to be notified when a UI is removed from the session.

Maybe the best solution would be to make this configurable via a general vaadin property (https://vaadin.com/docs/flow/advanced/tutorial-all-vaadin-properties.html)?

**Comment by pleku** [comment]
>One use case is to override onDetach to be notified when a UI is removed from the session.

Would a sufficient workaround be to get the `UI` instance in _where ever you want to be notified_ (?) and add a detach listener to it,:
```java
// inside a component:
getUI().ifPresent(ui.addDetachListener(event -> doStuffWhenUIRemoved());
```
But if you are using a "root layout" in your app, I think it should be enough to just override the `onDetach` method there as it is triggered too when the UI belongs to is detached.

**Comment by sniffertine** [comment]
Oh, I was not aware that the normal detach event is also fired here... But as I now follow the call hierarchy, I understand that this must be the way, thank you!
