### ISSUE TITLE
Fallback chunk not loaded in production mode

### ISSUE THREAD

**Issue by joheriks** [vaadin/spring#662]
**To reproduce**

Clone Spring [starter](https://github.com/vaadin/skeleton-starter-flow-spring), then replace MainView ctor with:
```java
try {
    Class c = Class.forName("com.vaadin.flow.component.checkbox.Checkbox");
    add((Component) c.newInstance());
} catch (Exception e) {
    e.printStackTrace();
}
```
Creating a `CheckBox` using reflection will evade the bytecode scanning and force use of the fallback chunk in production mode (and in development mode if `devmode.optimizeBundle` is true). Start app in production mode (profile `production`). 

**Observed behavior**: the added checkbox has no shadow root, meaning that it's frontend module is not loaded.

**Expected behavior**: the component frontend code should have been loaded via the fallback chunk.

**Versions**: Vaadin 14.3, Vaadin 17

See https://vaadin.com/forum/thread/18445598/production-mode-doesn-t-work-while-everthing-works-well-in-development-mode for details.

**Comment by yurili8** [comment]
Unfortunately， the latest relase of 14.4.0 doesn't include this fix.

**Comment by joheriks** [comment]
@yurili8 The fix didn't make it for the `14.4.0` platform release, but will be in the next maintenance release (`14.4.1`). Until then, you can add an explicit dependency on `vaadin-spring:12.3.2`.

**Comment by joheriks** [comment]
@yurili8 https://github.com/vaadin/platform/releases/tag/14.4.1

**Comment by yurili8** [comment]
> @yurili8 https://github.com/vaadin/platform/releases/tag/14.4.1

Thanks very much，I will have a try.
