### ISSUE TITLE
add a helper to configure Spring Security for Vaadin

### ISSUE THREAD

**Issue by vlukashov** [vaadin/spring#678]
When using Vaadin in a Spring Boot application with Spring Security, I want to have helper methods like `VaadinSpringSecurity.configure(http)` and `VaadinSpringSecurity.configure(web)` so that configuring spring security is a one-liner as opposed to the current best practice recommendation of:
```java
http.authorizeRequests()
        // allow anonymous access to the index page and static assets
        .antMatchers("/", 
        "/VAADIN/**", 
        "/vaadinServlet/**", 
        "/images/**", 
        "/icons/**", 
        "/manifest.webmanifest",
        "/sw.js",
        "/offline.html").permitAll()
        // all other requests
        .anyRequest().authenticated()
        .and().oauth2ResourceServer().jwt();
```

**Comment by knoobie** [comment]
This can be done by defining a custom `RequestMatcher`. See `org.springframework.boot.autoconfigure.security.servlet.PathRequest#toStaticResources()` as an example. 

It's often used like this:

```java
    http
      .authorizeRequests()       
         // Permit access to static resources
        .requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll()
        // Permit access to /login
        .antMatchers("/login**").permitAll()
        // Secure everything else
        .antMatchers("/**").authenticated()
```

It would be good to have different matchers, one for static files and one for internal vaadin communications.

**Comment by jcgueriaud1** [comment]
I'm not sure if we should allow the VAADIN folder to anonymous access. It allows the upload folder to anonymous and is a problem if you want be access to the user when you use the upload listener.

https://vaadin.com/learn/tutorials/securing-your-app-with-spring-security/speciale#_can_you_trust_vaadin_upload

https://github.com/vaadin/starters/issues/15

**Comment by knoobie** [comment]
The important part of your suggestion is "don't use configure(web) because this isn't processed by the security filter chain". I can 100% agree to that. It costed me a whole day to debug that once..

**Comment by Legioth** [comment]
> I'm not sure if we should allow the VAADIN folder to anonymous access.

Some part of `/VAADIN` might be necessary to pass through whereas other parts might make sense to block.

**Comment by vlukashov** [comment]
Implementation note: by using the `SpringFactoriesLoader` mechanics, all the default Vaadin-specific Spring Security configuration could be applied fully automatically, without developers even having to add a `SecurityConfiguration extends WebSecurityConfigurerAdapter` class to their apps.

This is how the DX would look like:
 - create a spring-boot project
 - add dependencies to `spring-boot-starter-security` and `vaadin-spring-boot-starter` into `pom.xml`
   ```xml
    <dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>vaadin-spring-boot-starter</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
   ```
 - that's it

When the app starts it will have the http and web security configured to handle all Vaadin-specific requests: CSRF, access to the app shell, webapp manifest, service worker, JS bundles, access to any route, etc.

If the developer wants to customize the security config, that's still possible by creating a `SecurityConfiguration extends WebSecurityConfigurerAdapter` class and overriding the `configure(http)` and `configure(web)` methods there. The default Vaadin-provided config would still be there.

**Comment by Legioth** [comment]
>The default Vaadin-provided config would still be there.

Can we be certain that anything that Vaadin has put there will be overrideable by the application if necessary? What should a developer do if they don't trust our automatic configuration and instead want to be in full control?

**Comment by vlukashov** [comment]
> > The default Vaadin-provided config would still be there.
> 
> Can we be certain that anything that Vaadin has put there will be overrideable by the application if necessary? What should a developer do if they don't trust our automatic configuration and instead want to be in full control?

I think that's exactly how Spring Security config works: any defaults set by `AbstractHttpConfigurer`s through the `SpringFactoriesLoader` API could be overridden in developer's `configure(http)` method.

In addition to that Vaadin could introduce a way to disable the auto-configuration. It could either be done as a property in `application.properties` or by moving the Vaadin's `AbstractHttpConfigurer` registration into a separate .jar and then explicitly excluding it in `pom.xml`.

**Comment by knoobie** [comment]
Personally I would prefer the explicit way of configuring spring security all in one file without any "magic". Meaning good documentation which requests vaadin needs or a custom `RequestMatcher` for vaadin is enough for me. 

Hiding such important detail as security behind auto-configuration doesn't feel worth the trouble this can bring.

**Comment by haijian-vaadin** [comment]
Decided one-liner helper mentioned in the description. which uses custom matcher(s) to match the static files and internal communications. Both the helper method and the matcher should be public.
Should also update the documentation/starters.
should also backport to V14.
