### ISSUE TITLE
Remove /vaadinServlet/* Spring Security bypass

### ISSUE THREAD

**Issue by Artur-** [vaadin/spring#789]
Even though there are no known issues it cause except the unlikely scenario that you map a vaadin servlet to something else than `/*` and secret resources to `/vaadinServlet/*`, the bypass should not be needed.

Currently the dev mode gizmo and maybe the normal push connection uses the URL directly. That should be changed

**Comment by miguelatvaadin** [comment]
I use the "internal improvement" label as I have not found a better label for this issue
