### ISSUE TITLE
When extending VaadinServletConfiguration @Bean method vaadinServletRegistration() is package private

### ISSUE THREAD

**Issue by neelu-sarkar** [vaadin/spring#8]
Hi,

Just a small thing - we've extended VaadinServletConfiguration to create our own custom ServletRegistrationBean, but as this method can't be overridden Spring will create an unnecessary bean. 

I don't think it causes any issues as such - I haven't noticed any so far. I'm not sure if there is a workaround using boot to stop this bean being created.

Thanks

**Comment by hesara** [comment]
I'll try to address the underlying issue (using a customized servlet) in a way that would also make it easier to use Vaadin together with Spring MVC, Spring Actuator etc. and would enable easily disabling the default Vaadin servlet by defining a bean.

Currently, having the Vaadin servlet mapped to the context root swallows requests to Spring DispatcherServlet.

**Comment by neelu-sarkar** [comment]
Sounds great - thanks

Neelu

**Comment by hesara** [comment]
The swallowing of requests was addressed already in 1.0.0.beta3 - one can now mix Vaadin Spring Boot with e.g. Spring MVC, Actuator etc.
With the latest code in master, it should also be possible to override the creation of the servlet registration bean in the rare cases where that is needed for other purposes.
