### ISSUE TITLE
@RouteAlias - Repeatable annotations with non-SOURCE retention are not yet supported in Kotlin

### ISSUE THREAD

**Issue by SomboChea** [vaadin/spring#811]
Hi, **Vaadin team**

I have a problem with **Vaadin Flow** in Spring Boot and Kotlin with **RouteAlias** cannot repeat this annotation more than one. But in Java, it's working normally. I think it can be a problem with the Kotlin language. _What should I do, if I still want to use Kotlin for **RouteAlias** with repeatable annotation?_

- Support in Java (Work)
```java
@Route(value = BakeryConst.PAGE_STOREFRONT_ORDER_TEMPLATE, layout = MainView.class)
@RouteAlias(value = BakeryConst.PAGE_STOREFRONT_ORDER_EDIT_TEMPLATE, layout = MainView.class)
@RouteAlias(value = BakeryConst.PAGE_ROOT, layout = MainView.class)
```

- Not support in Kotlin (Not work)
```kotlin
@Route(value = BakeryConst.PAGE_STOREFRONT_ORDER_TEMPLATE, layout = MainView::class)
@RouteAlias(value = BakeryConst.PAGE_STOREFRONT_ORDER_EDIT_TEMPLATE, layout = MainView::class)
@RouteAlias(value = BakeryConst.PAGE_ROOT, layout = MainView::class)
```
_Kotlin on YouTrack issue_: [https://youtrack.jetbrains.com/issue/KT-12794](https://youtrack.jetbrains.com/issue/KT-12794)

**Language and Framework**
- Spring Boot: 2.4.5
- Kotlin: 1.4.32
- Vaadin: 14.6.1
- Vaadin Gradle: 0.14.6.0
- Gradle: 6.8.3

Thank you!

**Comment by mvysny** [comment]
Unfortunately Kotlin the language doesn't support repeatable annotations, exactly as you suggested. There's not much Vaadin can do about it unfortunately. As a workaround, you'll have to replicate what javac does behind the scenes, and use an appropriate `@Repeatable`-marked annotation, which in this case is `RouteAlias.Container`:

```kotlin
@Route(value = BakeryConst.PAGE_STOREFRONT_ORDER_TEMPLATE, layout = MainView::class)
@RouteAlias.Container(RouteAlias(value = BakeryConst.PAGE_STOREFRONT_ORDER_EDIT_TEMPLATE, layout = MainView::class),
RouteAlias(value = BakeryConst.PAGE_ROOT, layout = MainView::class))
```

**Comment by miguelatvaadin** [comment]
Hi @SomboChea ,

thanks for posting this issue. As @mvysny , it is not Vaadin related so I'll close this issue. 

Please feel free to post a comment if you think it should be reopened.

**Comment by SomboChea** [comment]
Okay, thank you 😊!
