### ISSUE TITLE
Update Spring Navigation tutorial for @ViewContainer

### ISSUE THREAD

**Issue by hesara** [vaadin/spring#84]
Update Spring Navigation tutorial to use @ViewContainer:  https://vaadin.com/wiki/-/wiki/Spring+Vaadin/III+-+Views+and+Navigation+with+Vaadin+Spring

**Comment by hesara** [comment]
Update both the tutorial text (to draft) and the GitHub project https://github.com/vaadin/spring-tutorial (branch autoconfigure-navigator)

**Comment by hesara** [comment]
The tutorial text should be moved to the GitHub project wiki (TBC: main project wiki or spring-tutorial project wiki).

**Comment by Artur-** [comment]
Why should it be moved to the wiki and not vaadin.com/docs where all documentation should be?
