### ISSUE TITLE
Test Spring Navigation support without Spring Boot

### ISSUE THREAD

**Issue by hesara** [vaadin/spring#92]
Test automatic configuration of navigation in a non-Boot application.

**Comment by hesara** [comment]
https://vaadin.com/wiki/-/wiki/Spring+Vaadin/I+b+-+Getting+started+with+Vaadin+Spring+without+Spring+Boot can be used as a basis for the test application.

**Comment by elmot** [comment]
https://github.com/vaadin/spring-demo7/pull/4
