### ISSUE TITLE
Merge this into https://github.com/vaadin/flow

### ISSUE THREAD

**Issue by Artur-** [vaadin/spring#922]
It should be a module inside the Flow project to make everything easier. Today if you make a breaking change, even if it is internal API, you need to first merge something into Flow that you know breaks this project. Then you wait for a snapshot, verify that this project no longer compiles and then you can fix it.

**Comment by joheriks** [comment]
When the Flow validation build is fully parallelised, make a test PR to Flow to see if this can be done without undue increase of the validation time.

**Comment by joheriks** [comment]
Decided:
- Release of Spring and Flow modules will occur simultaneously, sharing the same release notes
- V14 (Flow 2.7/2.8, Spring 12) will continue with separate repos
- No breaking project setup:  it should be possible to configure Vaadin apps to use / exclude Spring add-on in the same way as before (`vaadin-spring-boot-starter`)
- Spring add-on module will follow Flow version (from V23, Flow will follow Platform version)

TODO:
- [x] Test refactoring: need to move spring-tests out of spring module to root level
- [x] Update validation and release jobs on bender
- [x] Import the Git history from `spring` to `flow`: https://github.com/vaadin/flow/issues/12959
- [x] Mention in README that master is no longer developed, Spring has moved to Flow repo
- [x] Issue template explaining that tickets should go to Flow repo
- [x] Branch protection / warning against new PRs towards `master` in the spring repo

**Comment by Artur-** [comment]
In https://github.com/vaadin/flow/pull/13002
