### ISSUE TITLE
Spring Security integration is broken if vaadin.urlMapping is used

### ISSUE THREAD

**Issue by mstahv** [vaadin/spring#989]
In case one moves Vaadin url to something else, using e.g. following configuration property, one cannot log in to the Vaadin application anymore:

    vaadin.urlMapping=/vaadin/*

How to reproduce:

 1. Go to start.vaadin.com, chose Flow
 2. Create an app with access controlled view
 3. Add the above configuration to your application.properties file
 4. Run the app and try accessing vaadin app from http://localhost:8080/vaadin/ -> software redirects to /login (which obviously don't work)

**Comment by farhan00hm** [comment]
When i use vaadin.urlMapping=/vaadin/* the front end doesn't render in Firefox browser.

**Comment by joheriks** [comment]
## Acceptance criteria

- The redirect URL after login should also include `vaadin.urlMapping` value.
